### ISSUE TITLE
dateparser: year-last dates are being parsed as ranges

### ISSUE THREAD

**Issue by retorquere** [Juris-M/zotero#10]
01/01/1989 is parsed to { day: 1, year_end: '1989', day_end: 1, year: '1989' }. 11/2012 also fails.

**Comment by fbennett** [comment]
This has now been fixed. A replace() operation used to normalize markup before parsing was replacing only the first slash in a delimited date. It now replaces all occurrences, and things work like they are supposed to.

Note that Juris-M now uses the [citeproc-js date parsing module](https://bitbucket.org/fbennett/citeproc-js/src/tip/src/util_dateparser.js?at=default&fileviewer=file-view-default) directly.
