### ISSUE TITLE
Add `version` to legal_commentary in the UI

### ISSUE THREAD

**Issue by georgd** [Juris-M/zotero#100]
Austrian styles require version numbers of online commentaries to be included in the citation, formatted like the edition number. However, putting the version in the edition field is in conflict with the following requirement: The leg cit style demands the publication date not to be printed if a version number exists, whereas an edition number doesn‘t influence on printing the date (_Compare_ tests at https://github.com/georgd/jm-style-tests/blob/jm-legcit/jm-leg-cit-rechtsquellenverzeichnis-literaturverzeichnis/chapCommentaryOnline_test050.txt with version _with_ https://github.com/georgd/jm-style-tests/blob/jm-legcit/jm-leg-cit-rechtsquellenverzeichnis-literaturverzeichnis/chapCommentaryOnline_test049.txt with an edition number.)

Therefore, could you please add the `version` field to the `legal_commentary` type in the Juris-M UI?

**Comment by fbennett** [comment]
Can do. Just to check before we commit that, there is the option to put the
version in the extended locator. It is preferred to put the value in a
fixed field? (Pretty sure that the answer is yes, but to be very sure.)

**Comment by georgd** [comment]
Oh, the extended locator... I always tend to forget about that. But I don’t think, this option is too user friendly here: we have four types of data that play a similar role: edition, version number, update date, and loose-leaf issue. Putting one of them in the locator and all the others in fields doesn’t seem transparent to me. So, I think it’s best to put the version no. in a fixed field. This information can easily be pulled from the online source (if a translator existed for the database...).

**Comment by georgd** [comment]
I tried it and I think, it really should be a fixed field.

Also, do you see a possibility in adding a field for `container-title-short` to Chapter and Legal Commentary? This field is commonly needed in German language styles (not only Austrian ones) where, among others, festschrifts are usually cited with a short book-title instead of the actual book title (cf. https://github.com/georgd/jm-style-tests/blob/master/jm-leg-cit-rechtsquellenverzeichnis-literaturverzeichnis/chapFS_test011.txt).

**Comment by fbennett** [comment]
Dear Georg,

Understood about adding a version field.

On festschrift short titles, would it be an alternative to add "honoree" as
a creator?

Frank

**Comment by georgd** [comment]
Dear Frank, "honoree" as a creator is an option (which I find elegant, indeed) but only together with an additional field because there are two kinds of publication, "Festschrift" and "Gedenkschrift" (memorial publication), that are cited this way (for the latter, see https://github.com/georgd/jm-style-tests/blob/master/jm-leg-cit-rechtsquellenverzeichnis-literaturverzeichnis/chapGedS_test010.txt). The former is cited as `FS Kelsen`, the latter as `GedS Martens`. The type could be put in the `genre` field, which again would be needed in the UI.

**Comment by georgd** [comment]
Looking at style guides from Germany, I think, earlier or later a field for `container-title-short` will be necessary in Chapter, as they generally seem to use the short book-title in citations (and the full book-title in the bibliography).

Anyway, please add a field Short Book Title to Legal Commentaries.

**Comment by fbennett** [comment]
Understood. I'll take a closer look and get back if I have questions. Re "honoree," it looks like a candidate is already in there, as "recipient." Will that serve?

**Comment by georgd** [comment]
Yes, I think, the `recipient` can be used here, I don’t see any conflict (i.e. I don‘t see a use case for a recipient in chapters).

**Comment by fbennett** [comment]
Great -- I think I may have had festschrift in mind when I added that. I'll look into the other issues. (If you think it might be confusing to users, the label for "Recipient" could later be changed to "Honoree" or other.)

**Comment by fbennett** [comment]
Just realized I neglected to add a `versionNumber` field to `legalCommentary`. I also didn't merge your latest module and style PRs in today's release. I'll include both that in the next update.

**Comment by georgd** [comment]
Great, thank you! Do you have a plan when you will do the next update?

Also, may I ask you, what’s the least uncomfortable way for you when I want to contribute UI translations?

**Comment by fbennett** [comment]
Next update will probably go out later today. I've checked in the change, but a bunch of tests will need to be adjusted to lock it in.

I'm not immediately sure what the best channel is for locale changes generally. Locales are updated by (1) layering Zotero changes onto existing Jurism source, then (2) generating and then applying a patch that changes "Zotero" to "Jurism" as appropriate across all locales. I'm not sure offhand what the priority is at step (1) in the event of conflict --- whether Jurism source is left untouched, or overridden by Zotero strings. For any Jurism-only strings, though (which will be set in English across all locales, as a placeholder), changes to the Jurism source will not be overridden. For those strings, a PR to `chrome/locale/xx-XX/zotero` under https://github.com/juris-m/zotero will definitely do the trick.

**Comment by georgd** [comment]
Thanks! So, I’ll stick with modifying those files.

**Comment by fbennett** [comment]
Running tests now, release forthcoming.
