### ISSUE TITLE
Updated translations don’t appear

### ISSUE THREAD

**Issue by georgd** [Juris-M/zotero#103]
After upgrading Juris-M to 5.0.93m5, the updated translations to chrome/locale/de/zotero/zotero.properties don’t show. Are localisations cached somewhere or were they simply not included in the latest release?

**Comment by fbennett** [comment]
It looks like I just screwed up and failed to push the code after merging
your changes. Version 5.0.93m6 is now up for the Mac, will follow with
Linux and Windows builds later (after dinner).

Frank

**Comment by fbennett** [comment]
Linux and Windows are up as well. I checked, the new translations seem to be in place now. Thanks for the heads-up!

**Comment by georgd** [comment]
Thank you very much!

**Comment by georgd** [comment]
Hmm, I still don’t get the new translations. Neither on Windows nor on Mac.

**Comment by georgd** [comment]
@fbennett In https://github.com/Juris-M/zotero-schema/pull/3 you mention a script that shuffles data around. Could that be the culprit here?

**Comment by fbennett** [comment]
Just to be sure we're looking in the same place, could you send along a
screenshot?

**Comment by georgd** [comment]
Here, 'Legal Commentary' should read 'Gesetzeskommentar' and 'Book Abbrev' should read 'Buch-Kurztitel':

![image](https://user-images.githubusercontent.com/214002/100515165-4185f000-317a-11eb-813a-044b2d58e906.png)

**Comment by fbennett** [comment]
Ah, sorry. I was living in the past. The client used to access locales from `chrome/locale/xx-XX/zotero/`, but they are now copied from there to `resource/schema/global/schema.json` (`resource/schema/global/schema-jurism.json` in Jurism) by the setup script at `resource/schema/global/scripts/update-schema`. As you suggested, that script (which in Jurism serves double-duty as the patch mechanism for Jurism extended fields) needed running before the build. The Mac build that just went live should give you the new field labels in the German locale.

**Comment by georgd** [comment]
Great, it’s there now :)

For future changes, should I still update translations in `chrome/locale/xx-XX/zotero/` or anywhere else?

**Comment by fbennett** [comment]
Your changes were perfect. I just missed that step in preparing the
releases.
