### ISSUE TITLE
Detect invalid jurisdiction values

### ISSUE THREAD

**Issue by georgd** [Juris-M/zotero#105]
In https://github.com/Juris-M/zotero/issues/104 I described how invalid values in `jurisdiction` broke Word integration.

These entries very probably happened when switching from Zotero to Juris-M. Is there a way to detect invalid entries? I expect more of them to come up in the near future as I’m anticipating an entire institute to do that switch.

**Comment by fbennett** [comment]
The ``5.0.93m13`` release includes the following fixes:
* Jurisdiction fields with invalid underlying values will show up highlighted in yellow, to flag that they need to be reentered.
* As a UX improvement, selecting a jurisdiction from the search (or arrow-down) listing can now to done from the keyboard, by navigating to the target value with the arrow keys and hitting Enter.
* Invalid values will no longer crash the abbrevs filter or citation processor.
