### ISSUE TITLE
DE translation vanished

### ISSUE THREAD

**Issue by georgd** [Juris-M/zotero#107]
Yesterday’s update undid again translation updates. I think, this happened here: https://github.com/Juris-M/zotero-schema/commit/99594640817a8c4b1c497a1399441298e452d89a @fbennett could you please undo that commit?

**Comment by fbennett** [comment]
Whaaat? Sorry about this. I'm really not understanding how locale-string updates work, then. The release was put through all of the steps that I understood would produce a correct reflection of your edits. So to begin my re-study of the entire subject ... the correct string for the first item is "Einreichungsnummer," and not "Bewerbungsnummer?"

**Comment by fbennett** [comment]
Perhaps we have crossed signals on the source of the UI locale strings. The canonical source is ``zotero.properties`` under ``chrome/local/XX/zotero``. The locale strings in the Jurism fork of ``zotero-schema`` are copied from ``zotero-properties``. The latest release included an update to the schema, which refreshed the locale strings from there.

Looking at the commits to ``chrome/locale/de/zotero/zotero.properties``, the string for ``itemFields.applicationNumber`` was changed from ``Einreichungsnummer`` to ``Bewerbungsnummer`` by pull request on November 28 (https://github.com/Juris-M/zotero/pull/102/commits/a7c3f5bc9e68bf83bc74c04262b7d6b5b1ed262d). The value hasn't been touched by any subsequent commit.

Sorry to put you to extra trouble, but if any labels showing through in the UI are now incorrect, could you file a pull request against ``chrome/locale/de/zotero/zotero.properties`` in this repo to fix them? The revisions will then show through in the next release.

**Comment by georgd** [comment]
Ok, I’ll create the PR.

>Looking at the commits to chrome/locale/de/zotero/zotero.properties, the string for itemFields.applicationNumber was changed from Einreichungsnummer to Bewerbungsnummer by pull request on November 28 (a7c3f5b). The value hasn't been touched by any subsequent commit.

What I see is, that https://github.com/Juris-M/zotero/commit/a7c3f5bc9e68bf83bc74c04262b7d6b5b1ed262d changed from `Bewerbungsnummer`  to `Einreichungsnummer` and the commit that changed the translations back was https://github.com/Juris-M/zotero/commit/baf5fa4851ec87a80da92eb0779094ee3628c30a "scaffold locale strings".

**Comment by fbennett** [comment]
Ah. I misread the first commit, and missed the change in the second. A pretty dismal performance. Jurism needs a release manager.

Thanks for the manual fix. I'll refresh the clients on the three platforms. 

(The latter commit revived Scaffold, which had been broken in Jurism since its integration. I'm not sure how those reversion got in there, but it shouldn't happen again.)
