### ISSUE TITLE
dateparser: does not recognize März 1, 2008

### ISSUE THREAD

**Issue by retorquere** [Juris-M/zotero#11]
I am feeding the date parser the following month array:

```
["januar","februar","märz","april","mai","juni","juli","august","september","oktober","november","dezember","frühjahr","sommer","herbst","winter"]
```

using `addDateParserMonths`, but `März 1, 2008` is being parsed to `{ "year": "2008", "day": 1 }`. I have a test page up that uses the latest dateparser from this repo at https://zotplus.github.io/better-bibtex/dateparser.html. For dutch dates like `maart 1, 2008` it does do what I expect.

**Comment by retorquere** [comment]
The date is not being tokenized correctly; I think line 585 is the culprit, as it only understands ascii strings.

**Comment by retorquere** [comment]
Sorry, that should be line [394](https://github.com/Juris-M/zotero/blob/jurism/chrome/content/zotero/xpcom/dateparser.js#L394)

**Comment by fbennett** [comment]
Ugh, that wasn't very clever, was it. Looks like something like this would fix it ...

> `m = item.match(/^\s*([\-\/]|[^\-\/\~\?0-9]+|[\-~?0-9]+)\s*$/);`

Does that look right?

**Comment by retorquere** [comment]
Not entirely, because the items offered to that match are, in order

```
''
'M'
'ä'
'rz'
' '
'1'
', '
'2008'
''
```

**Comment by retorquere** [comment]
That in turn looks to have something to do with https://github.com/Juris-M/zotero/blob/jurism/chrome/content/zotero/xpcom/dateparser.js#L108

**Comment by fbennett** [comment]
Oh, pshaw. I'll build tests this evening and come up with something better there.

**Comment by fbennett** [comment]
This was fixed awhile ago, I think, thanks to your amendments. Closing the issue now during housecleaning.

Note that Juris-M now uses the [citeproc-js date parsing module](https://bitbucket.org/fbennett/citeproc-js/src/tip/src/util_dateparser.js?at=default&fileviewer=file-view-default) directly.
