### ISSUE TITLE
dateparser: errors out on 四月 1, 1976

### ISSUE THREAD

**Issue by retorquere** [Juris-M/zotero#13]
The dateparser errors out [here](https://github.com/Juris-M/zotero/blob/jurism/chrome/content/zotero/xpcom/dateparser.js#L334) because [txt.match](https://github.com/Juris-M/zotero/blob/jurism/chrome/content/zotero/xpcom/dateparser.js#L332) returns undefined. Changing the latter line to `var mm = txt.match(jiymatcher) || [];` makes the dateparser run without error, but I don't know what the side effects of doing this are.

**Comment by fbennett** [comment]
Thanks - I'll check into it at the weekend. That wouldn't be a valid date, so returning it literal will probably be the best result. Sounds like the match for `mm` is too aggressive given the `m` match on which (I assume blindly, without looking at the code) it depends.

(Or maybe something else - but throwing an error is definitely not good.)

**Comment by retorquere** [comment]
I have no idea what that date actually says, just that it's out there as a user has it in his library. The `|| []` workaround gets me going for now, but it was a blunt fix, and I have no idea what damage it does.

Thanks for looking into it.

**Comment by fbennett** [comment]
The code is messy and needs to be cleaned up. There are separate date parsing functions in `citeproc-js` and `Juris-M`, and they have diverged. The former is tested regularly with the balance of the processor code, and it does not error out on that input. The structural messiness of the function in `Juris-M` apparently made it difficult to just call the module from CSL, but that's clearly what should be done. I have some time this evening to work on it, I'll see if I can straighten things out.

**Comment by fbennett** [comment]
Cleanup now complete (well, the first pass of it, anyway).

This is trying to say "Apr 1, 1976" with a mixture of Japanese/Chinese and Western date syntax, but with the crash avoided, the parser only picks up the year and the day. It down bails to literal unless a complete date is found.

Note that Juris-M now uses the [citeproc-js date parsing module](https://bitbucket.org/fbennett/citeproc-js/src/tip/src/util_dateparser.js?at=default&fileviewer=file-view-default) directly.
