### ISSUE TITLE
Juris-M not compatible with Firefox 38.7.0

### ISSUE THREAD

**Issue by elbasi88** [Juris-M/zotero#15]
I had been using Multilingual Zotero for a long time, but after a Zotero update, it wouldn't work anymore. I then wanted to re-install the original version of MLZ that I had been using, but it seems the download doesn't work anymore (the site http://citationstylist.org/tools/ just isn't loading). I then read that Juris-M has kind of replaced MLZ and was excited about it, but when I tried installing it, I was notified that "Juris-M could not be installed because it is not compatible with Firefox 38.7.0".

Unfortunately, I cannot change my current version of Firefox because it is administered by my university's IT department, I already asked them and they were reluctant to do so. Downloading the standalone version of Juris-M worked, but I really need the Firefox plugin to efficiently manage and extend my Zotero library. Also, the regular Zotero is not an option for me because I have a lot of Chinese sources where I need the multilingual functions.

Any ideas on how to solve this problem? Many thanks in advance!

**Comment by fbennett** [comment]
Thanks for alerting me to this. Zotero permits installs back to FF 38, and there is no reason Juris-M should not do the same. A new release of everything will be out within the next could of days, and I'll change this setting everywhere. In the meantime, I'll refresh the current release as-is - you should be able get it by updating the plugin a few minutes after you receive this message.

**Comment by fbennett** [comment]
The refreshed version (jurism-v4.0.28.7m58) is now up, and should run for you. I'll refresh the other plugins while I'm at it - and my apologies for the interruption.

**Comment by fbennett** [comment]
The plugins have all been updated, and should run in Firefox 38 without error. Let me know if you hit any snags.

**Comment by elbasi88** [comment]
Thank you so much, you are amazing! It works perfectly! :)
