### ISSUE TITLE
Better BibTeX in Juris-M

### ISSUE THREAD

**Issue by retorquere** [Juris-M/zotero#16]
I've tried installing the latest BBT in Juris-M, but I'm getting this error when I import some items (using the debug translator built into BBT). I've tried figuring out what the relevant differences are between Zotero 4.0 and Juris-M, but the code mentioned in the trace seems very similar:

```
(2)(+0000000): Translate: Translation using BetterBibTeX JSON failed:
string => Error: Invalid field 'false' in ItemFields.isBaseField()
stack => _fieldCheck@chrome://zotero/content/xpcom/data/itemFields.js:410:1
isBaseField@chrome://zotero/content/xpcom/data/itemFields.js:216:3
Zotero.Utilities.itemFromCSLJSON@chrome://zotero/content/xpcom/utilities.js:2342:8
Zotero.Translate.ItemSaver.prototype._saveFields@chrome://zotero/content/xpcom/translation/translate_item.js:674:4
Zotero.Translate.ItemSaver.prototype.saveItems@chrome://zotero/content/xpcom/translation/translate_item.js:132:7
Zotero.Translate.Base.prototype._saveItems@chrome://zotero/content/xpcom/translation/translate.js:1425:1
Zotero.Translate.Sandbox.Base._itemDone@chrome://zotero/content/xpcom/translation/translate.js:150:5
Zotero.Translate.SandboxManager.prototype.importObject/attachTo[localKey]<@chrome://zotero/content/xpcom/translation/translate_firefox.js:527:29
@resource://gre/modules/RemoteAddonsParent.jsm:761:66
Zotero.Item.prototype.complete@resource://gre/modules/RemoteAddonsParent.jsm:761:448
doImport@/tmp/webdriver-rb-profilecopy20160409-28874-rkupna/zotero/translators/BetterBibTeX JSON.js:1697:18
Zotero.Translate.Base.prototype._translateTranslatorLoaded@chrome://zotero/content/xpcom/translation/translate.js:1222:4
Zotero.Translate.Base.prototype.translate/<@chrome://zotero/content/xpcom/translation/translate.js:1189:58
Zotero.Translate.Import.prototype._loadTranslatorPrepareIO/initCallback@chrome://zotero/content/xpcom/translation/translate.js:2051:17
Zotero.Translate.IO.Read.prototype.init@chrome://zotero/content/xpcom/translation/translate_firefox.js:938:3
Zotero.Translate.Import.prototype._loadTranslatorPrepareIO@chrome://zotero/content/xpcom/translation/translate.js:2078:3
Zotero.Translate.Import.prototype._loadTranslator/<@chrome://zotero/content/xpcom/translation/translate.js:2034:3
Zotero.Translate.Base.prototype._loadTranslator@chrome://zotero/content/xpcom/translation/translate.js:1574:16
Zotero.Translate.Import.prototype._loadTranslator@chrome://zotero/content/xpcom/translation/translate.js:2033:2
Zotero.Translate.Base.prototype.translate@chrome://zotero/content/xpcom/translation/translate.js:1189:4
Zotero_File_Interface</_importTranslatorsAvailable/<@chrome://zotero/content/fileInterface.js:355:5
```

**Comment by fbennett** [comment]
It may take a few days for me to get to it, but I should be able to help. How can I go about running the tests?

**Comment by retorquere** [comment]
I've just put up an explanation on how to run the BBT test suite on my [wiki](https://github.com/retorquere/zotero-better-bibtex/wiki/Debugging). In the case of Juris-M there are just a few changes.
1. After cloning, checkout the `475` branch. This is just current master, but it has a few tweaks so Juris-M is available as an option in addition to Zotero.
2. Set JURIS_M=true in your environment. This will cause the test runner (in the 475 branch, I haven't merged it yet, but I will) to grab Juris-M instead of Zotero. Something like `JURIS_M=true SIGN=false rake test` should do the job.

The circle.yml in that branch has JURIS_M set to true; I think it will just work if you flick the switch in your clone, but I haven't tried.

Thanks for looking into this!

**Comment by retorquere** [comment]
You probably know BBT is a little immodest about going in and groping around -- I don't expect you to just get BBT working, but I seriously don't understand what's failing above, and that error is in the setup for the first test.

But my initial report was misleading. The bulk of the tests [actually pass](https://circleci.com/gh/retorquere/zotero-better-bibtex/2181), and some of the failing tests are not hard to address. The test that failed just happened to be a) big and b) the first. It's still odd though. It fails at the import part (that part I got right above), but all tests run this part in one way or the other. Why it should flame out in that part of these tests is still a mystery to me.

**Comment by retorquere** [comment]
Interesting -- _CSL title, volume-title, container-title=BL title, booktitle, maintitle #381_ appears to fail because (I think) Juris-M strips out `volume-title: ...` from the extra field before BBT sees it. Is that information available elsewhere to the translator?

**Comment by retorquere** [comment]
No, that isn't right, the data is still there. NM.

**Comment by fbennett** [comment]
Yeah, it could take me awhile to set up your test framework, and from the docs it sounds like it would be hard to do my usual thing of sticking comments in the code to try hypotheses. Is there an operation I can perform user-side in a client with BBT installed that will trigger the failure you're seeing?

**Comment by retorquere** [comment]
I haven't tried, but you should be able to unzip the [latest release](https://github.com/retorquere/zotero-better-bibtex/releases/tag/1.6.45) and run it as per [running git installations](http://webcache.googleusercontent.com/search?q=cache:5P_nu2gsqIwJ:www.zotero.org/support/dev/source_code+&cd=2&hl=en&ct=clnk&gl=nl). Just make sure that any changes you want to make to the translators you make in the bundled `.translator` files in `resource/translators`, not to the ones that get installed into the Zotero translators directory, as BBT overwrites those every time it starts up.

The translator files are big as a lot of cruft gets bundled in because I need them inside the sandbox; most of the code is library code, I've marked the sections by `SOURCE:` comments. And they're generated from coffeescript sources, so it's not always the prettiest JS to look at.

Comments is how I usually do it though, except I put the comments in coffeescript code. I know of no other way, but I haven't actually tried the Mozilla debugger. Huh.

**Comment by fbennett** [comment]
Actually, this looks like a straight-up bug in Juris-M code. I owe you.

From the steps in the trace at the top of this thread, it looks like it's failing on a date variable. Juris-M adds a bunch of date variables to the schema (schema changes [here](https://github.com/Juris-M/zotero/blob/jurism/resource/schema/system.sql#L352), mappings to CSL [here](https://github.com/Juris-M/zotero/blob/jurism/chrome/content/zotero/xpcom/utilities.js#L107)). It looks like it's finding a date variable okay (so it has a value for `field` in [utilities.js](https://github.com/Juris-M/zotero/blob/jurism/chrome/content/zotero/xpcom/utilities.js#L2338)), but then it's not finding an ID for it, so `fieldID` in that function is set to `false`. When that is fed to `isBaseField()`, it blows up. It's a little confusing if the code is read by following functions from the top of the trace, because the `field` argument in [`Zotero.ItemFields.isBaseField()`](https://github.com/Juris-M/zotero/blob/jurism/chrome/content/zotero/xpcom/data/itemFields.js#L215) is actually coming from the `fieldID` variable in the calling code.

Anyway, that all points clearly to a mismatch in my code. There _must_ be a date variable in the mappings that is not included in the schema. I'll look into this, it should be an easy fix.

**Comment by fbennett** [comment]
Oh, jeez, bingo. The Z->CSL date mappings in Zotero are one-to-one, but Juris-M maps one-to-many: the mapping is to an array. So I need to step through those values, but instead I'm treating them as string variables (keys) in their own right. No way that could work.

I do remember covering this issue, but I must have missed this bit, or the code got reversed at some point. The next Juris-M release should do better for you.

**Comment by retorquere** [comment]
Cool. Also thanks for the pointer to the fields, I have no idea yet how any of those map out to BibTeX, but from the looks of it they should at least be easy to access.

I hadn't thought to look in the schema. It makes sense that the different schema might affect otherwise same or similar code.

What is the meaning of the `meta` hash that's sometimes included in the `author` data? The only time I've seen it it has value `{ '_key': {} }`

Do you know of any BibTeX-specific stuff when it comes to legal citation?

**Comment by fbennett** [comment]
The `multi` segment is attached to the item, and to individual creators. It carries multilingual variants and language tags dependent on a headline field. It's used both in Zotero items and in CSL JSON (the structures are the same, but in a Z item schema IDs are used, while CSL JSON uses fieldnames). For a field it looks like this when used (`main` can hold language tags of the headline fields themselves):

``` javascript
{
    'id': 'muzzlemuzzle',
    'title': 'Title in English',
    'multi': {
        'main': {
            'title': 'en'
        }
        '_keys': {
            'title': {
                'ja-JP': '日本語の題名'
             }
        }
    }
}
```

For creators, the 'field' is known, so the structure is a little simpler. To help keep myself straight on the two, creators use a '_key' hash (singular):

``` javascript
{
    'given': 'Frank',
    'family': 'Bennett',
    'multi': {
        'main': 'en',
        '_key': {
            'ja-alalc97': {
                'given': 'フランク',
                'family': 'ベネット'
            }
        }
    }
}
```

**Comment by fbennett** [comment]
On legal LaTeX, you might check out the [discussion list](https://plus.google.com/u/0/communities/117481232881578280631) hosted by Alan Feldman in New York (he is a New York attorney, and uses LaTeX in his practice). I think the leading package for law is [jurabib](https://www.ctan.org/pkg/jurabib), but I don't know much about it.

Years ago, I [fashioned something](https://www.tug.org/TUGboat/tb14-3/tb40bennett.pdf) out of BibTeX that could sort of handle "Bluebook citations." I stuck with it for awhile, taking it through [one major revision](https://www.tug.org/TUGboat/tb17-1/tb50benn.pdf), but finally let it go. Law doesn't lend itself to the BibTeX data model; in the US alone, there are over a dozen discrete styles for referencing cases, depending on the jurisdiction in which they are cited. Internationally, the situation is much worse. The only way to handle it without going nuts is to load jurisdiction-specific styles on demand, which is what I do in `citeproc-js`. It's been like taking off a tight pair of shoes.

For really robust legal support in LaTeX, I think it would make sense to build a wrapper around `citeproc-js`, and run it as a drop-in replacement for BibTeX, applying CSL (or CSL-M) styles directly to LaTeX source documents. Looking at Oren Patashnik's piece on the desiderata for [BibTeX 1.0](https://tug.org/TUGboat/tb24-1/patashnik.pdf), `citeproc-js` covers all of them. Implementing a wrapper would get you there in one go. Lots of leverage to be had, I figure someone will eventually give it a try.

**Comment by retorquere** [comment]
Wow, not going there. Perhaps then just support for people who want to use Juris-M in Zotero BibTeX mode.

I do remember one of my users pulling out a bibliography over the embedded webserver using a custom CSL style. Someone might already be doing it.

**Comment by fbennett** [comment]
I've put up a new beta ([jurism-v4.0.29.6m64beta7-fx.xpi](https://github.com/Juris-M/zotero/releases/tag/v4.0.29.6m64beta)) that is meant to fix this. Haven't tested it, but this _should_ get you past that error.

**Comment by fbennett** [comment]
Have now managed to break CSL JSON import in the old Juris-M client version, on a date record that now clears under beta7, so the basic error should definitely go away. The BibTeX recorded on import is `_us_????`, though, so maybe some tweak will be needed there. Thanks so much for reporting this, that was an ugly bug.

**Comment by retorquere** [comment]
My pleasure, glad I didn't waste your time. Tests are running on b7.

What do you mean by "The BibTeX recorded on import"?

**Comment by retorquere** [comment]
I'm now getting

```
(1)(+0000001): TypeError: Zotero.EXTENDED_FIELDS[zoteroType] is undefined
    ===== Stack Trace =====
    Zotero.Utilities.itemFromCSLJSON@chrome://zotero/content/xpcom/utilities.js:2343:1
    Zotero.Translate.ItemSaver.prototype._saveFields@chrome://zotero/content/xpcom/translation/translate_item.js:674:4
    Zotero.Translate.ItemSaver.prototype.saveItems@chrome://zotero/content/xpcom/translation/translate_item.js:132:7
    Zotero.Translate.Base.prototype._saveItems@chrome://zotero/content/xpcom/translation/translate.js:1425:1
    Zotero.Translate.Sandbox.Base._itemDone@chrome://zotero/content/xpcom/translation/translate.js:150:5
    Zotero.Translate.SandboxManager.prototype.importObject/attachTo[localKey]<@chrome://zotero/content/xpcom/translation/translate_firefox.js:527:29
    @resource://gre/modules/RemoteAddonsParent.jsm:761:66
    Zotero.Item.prototype.complete@resource://gre/modules/RemoteAddonsParent.jsm:761:448
    doImport@/tmp/webdriver-rb-profilecopy20160410-24364-1d0qeyx/zotero/translators/BetterBibTeX JSON.js:1697:18
    Zotero.Translate.Base.prototype._translateTranslatorLoaded@chrome://zotero/content/xpcom/translation/translate.js:1222:4
    Zotero.Translate.Base.prototype.translate/<@chrome://zotero/content/xpcom/translation/translate.js:1189:58
    Zotero.Translate.Import.prototype._loadTranslatorPrepareIO/initCallback@chrome://zotero/content/xpcom/translation/translate.js:2051:17
    Zotero.Translate.IO.Read.prototype.init@chrome://zotero/content/xpcom/translation/translate_firefox.js:938:3
    Zotero.Translate.Import.prototype._loadTranslatorPrepareIO@chrome://zotero/content/xpcom/translation/translate.js:2078:3
    Zotero.Translate.Import.prototype._loadTranslator/<@chrome://zotero/content/xpcom/translation/translate.js:2034:3
    Zotero.Translate.Base.prototype._loadTranslator@chrome://zotero/content/xpcom/translation/translate.js:1574:16
    Zotero.Translate.Import.prototype._loadTranslator@chrome://zotero/content/xpcom/translation/translate.js:2033:2
    Zotero.Translate.Base.prototype.translate@chrome://zotero/content/xpcom/translation/translate.js:1189:4
    Zotero_File_Interface</_importTranslatorsAvailable/<@chrome://zotero/content/fileInterface.js:355:5
    =======================
```

**Comment by fbennett** [comment]
What is the value of zoteroType?

(By BibTeX record, I just meant the input record that triggers the error.)

**Comment by fbennett** [comment]
There is another obvious flaw in the Juris-M code here, though. Not all Zotero types have been extended, so when no extension information is found, it should drop out of what it wants to do there. [Beta8](https://github.com/Juris-M/zotero/releases/tag/v4.0.29.6m64beta) is now up, hope it does better.

**Comment by retorquere** [comment]
Do you mean a specific test case of mine when you say "BibTeX record..."?

How can I log the value of zoteroType? As I usually do I monkey patched the function to inspect what's going in and out, but It's an internal var to Zotero.Utilities.itemFromCSLJSON. I can see that cslItem.type = webpage when itemFromCSLJSON is being called, so zoteroType _should_ be webpage if I follow that code correctly.

But beta8 does resolve this error, huzzah! Tests are running again. I can already see there are differences between the Zotero and the Juris-M date-parser causing me to not find dates on some items, or perhaps it's due to the dates being in another field, but that shouldn't be hard to resolve.

**Comment by retorquere** [comment]
There _is_ something funny going on with CSLvars in the extra field though. All the tests that rely on those values being there currently fail.

**Comment by fbennett** [comment]
At least we've gotten past the obvious things. I'm doing some writing tonight, and won't be able to look at it, but I'll keep it in thought, might send a note tomorrow morning.

**Comment by retorquere** [comment]
I should totally be doing some writing tonight and every night for the coming weeks. This is my guilty pleasure... generally good news though, no more errors on importing objects, just exports, and of the 138 tests, 130 pass.

**Comment by fbennett** [comment]
Oooh. Juris-M scores a B+!

**Comment by retorquere** [comment]
If I import the attached file, which is a CSL-JSON file exported using Juris-M (no BBT or anything else installed), I get:

```
(1)(+0000000): TypeError: creator.multi._lst is undefined
    ===== Stack Trace =====
    Zotero.Translate.ItemSaver.prototype._saveCreators@chrome://zotero/content/xpcom/translation/translate_item.js:724:9
    Zotero.Translate.ItemSaver.prototype.saveItems@chrome://zotero/content/xpcom/translation/translate_item.js:136:8
    Zotero.Translate.Base.prototype._saveItems@chrome://zotero/content/xpcom/translation/translate.js:1425:1
    Zotero.Translate.Sandbox.Base._itemDone@chrome://zotero/content/xpcom/translation/translate.js:150:5
    Zotero.Translate.SandboxManager.prototype.importObject/attachTo[localKey]<@chrome://zotero/content/xpcom/translation/translate_firefox.js:527:29
    @resource://gre/modules/RemoteAddonsParent.jsm:761:66
    Zotero.Item.prototype.complete@resource://gre/modules/RemoteAddonsParent.jsm:761:448
    doImport@/home/emile/.mozilla/firefox/mjaevy0p.Juris-M/zotero/translators/CSL JSON.js:63:3
    Zotero.Translate.Base.prototype._translateTranslatorLoaded@chrome://zotero/content/xpcom/translation/translate.js:1222:4
    Zotero.Translate.Base.prototype.translate/<@chrome://zotero/content/xpcom/translation/translate.js:1189:58
    Zotero.Translate.Import.prototype._loadTranslatorPrepareIO/initCallback@chrome://zotero/content/xpcom/translation/translate.js:2051:17
    Zotero.Translate.IO.String.prototype.init@chrome://zotero/content/xpcom/translation/translate.js:2547:4
    Zotero.Translate.Import.prototype._loadTranslatorPrepareIO@chrome://zotero/content/xpcom/translation/translate.js:2078:3
    Zotero.Translate.Import.prototype._loadTranslator/<@chrome://zotero/content/xpcom/translation/translate.js:2034:3
    Zotero.Translate.Base.prototype._loadTranslator@chrome://zotero/content/xpcom/translation/translate.js:1574:16
    Zotero.Translate.Import.prototype._loadTranslator@chrome://zotero/content/xpcom/translation/translate.js:2033:2
    Zotero.Translate.Base.prototype.translate@chrome://zotero/content/xpcom/translation/translate.js:1189:4
    Zotero_File_Interface</_importTranslatorsAvailable/<@chrome://zotero/content/fileInterface.js:355:5
    =======================
```

[Exported Items.txt](https://github.com/Juris-M/zotero/files/211893/Exported.Items.txt)

**Comment by retorquere** [comment]
**[A]** The problem with the missing fields is not an import issue -- Juris-M strips out CSL fields in the extra field during import. Try importing this attachment (it's in Zotero RDF format) -- it has `{:issued:2014-12-31/2015-01-01}` in the `extra` field, but it doesn't show up in Juris-M.
[Exported Items.txt](https://github.com/Juris-M/zotero/files/211905/Exported.Items.txt)

**Comment by retorquere** [comment]
It's not an _export_ issue I meant to say. There's nothing to export.

**Comment by retorquere** [comment]
I've also tried MODS -- same deal.

**Comment by retorquere** [comment]
Ugh never mind on the RDF item, it puts it in the abstract. I've attached a BibTeX file exported with the stock translator -- not much roundtrips cleanly.

I think it happens at https://github.com/Juris-M/zotero/blob/jurism/chrome/content/zotero/xpcom/translation/translate_item.js#L660 . I've temporarily monkey-patched Zotero.Utilities.itemToCSLJSON and Zotero.Utilities.itemFromCSLJSON; I can see this being returned from Zotero.Utilities.itemToCSLJSON:

```
{"type":"webpage","multi":{"main":{},"_keys":{}},"system_id":"0_undefined","title":"Test","note":"{:issued:2014-12-31/2015-01-01}"}
```

And this coming out of Zotero.Utilities.itemFromCSLJSON, dumped using Zotero.Utilities.Internal.itemToExportFormat (which should give a good idea of what a translator would see):

legacy mode

```
{"itemType":"webpage","tags":[],"collections":[],"relations":{},"multi":{"main":{},"_keys":{}},"title":"Test","creators":[],"uri":"http://zotero.org/users/local/aMgNMAOC/items/null","attachments":[],"notes":[],"uniqueFields":{"title":"Test"},"itemID":null,"key":null,"dateAdded":null,"dateModified":null,"libraryID":null,"seeAlso":[]}
```

non-legacy:

```
{"version":0,"itemType":"webpage","tags":[],"collections":[],"relations":{},"multi":{"main":{},"_keys":{}},"title":"Test","creators":[],"uri":"http://zotero.org/users/local/aMgNMAOC/items/null","attachments":[],"notes":[]}
```

Given how Zotero.Utilities.itemFromCSLJSON works, I'd have expected `issued` to be mapped to a field called `date`, but neither form has that.

[Exported Items.txt](https://github.com/Juris-M/zotero/files/212023/Exported.Items.txt)

**Comment by fbennett** [comment]
Replying to individual comments doesn't seem to work here, but I can edit your entries for some reason. I tried the attachment in the comment that I have labeled **[A]** above, both in Juris-M and in Zotero (with BBT disabled), and I get the same result: export in Zotero RDF puts the Extra field content in a "description" node as a sibling to title, etc; and when the item is re-imported, that field content goes into the Abstract field (which can't be right).

I'm not sure what to do there. At first blush, it looks like a bug in the Zotero translator, but there might be a reason for it to behave that way?

Aha. And reading down, I see that you already know that. Late here, I'm going to get some sleep; but I'll read up on your work so far tomorrow, and see if there is anything to do or test at my end.

**Comment by retorquere** [comment]
Ah don't worry about the rdf, that has never roundtripped properly, it's the main reason I added my debug translator, as it's the only translator that does. Absent the bbt debug translator I usually pick csl-json (not
perfect but loads better than rdf when it comes to roundtripping), but Juris-M errors out when importing its own csl-json. That's why I tried rdf, having forgotten how bad it was.

**Comment by retorquere** [comment]
The main two issues are now a) csl-json import fails (not a problem for bbt, but you might want it to work) and b) the extra field is always stripped of csl-json vars, regardless of which import translator is in use (this breaks the bbt tests, as I need a way to import references that have these after import)

**Comment by retorquere** [comment]
Or alternatively I need to have access to the data they held in some other fields. But stripping the vars means bbt cannot test what happens if a user manually adds them in the extra field as I can't populate the database that way.

**Comment by fbennett** [comment]
Found it. During translation, the data in those brace-hack items is being parsed out correctly, but it's stored on the cslItem object as a plain string. When that's fed back to itemFromCSLJSON(), the string value is not valid, so it's dropped on the floor. This would affect both dates and names -- the two main field types for which the brace-hack is useful.

There is code elsewhere that does this parse correctly, so it's just a matter of finding that, casting it as a function if necessary, and then invoking the code during translation. Should have a fix up in a bit.

It should also be possible to improve results in Zotero RDF round-tripping. Zotero RDF sets extra as dc:description, and that's parsed out on import by RDF.js, which handles it as abstractNote, along with bazillion other RDF tags. If dc:description alone is translated as extra by the RDF.js import translator, the brace-hack fields should be recognized there as well. Not sure if that will pass muster in Zotero (RDF is full of mysteries for me), but if it's a hack, it seems a useful one.

More news in a bit ...

**Comment by fbennett** [comment]
Okay, I have a fix running. The code is in an installed instance of Juris-M, so I'll need to diff it out and merge to the actual source, but we're nearly there.

The fix will apply to both CSLJSON, and to Zotero RDF if the RDF.js translator is patched to put the Extra field data in the right place. I tested with the latter, but it runs itemFromCSLJSON() implicitly, so both translators should be okay.

More soon-ish ...

**Comment by fbennett** [comment]
Okay, I have a fix running. The code is in an installed instance of Juris-M, so I'll need to diff it out and merge to the actual source, but we're nearly there.

The fix will apply to both CSLJSON, and to Zotero RDF if the RDF.js translator is patched to put the Extra field data in the right place. I tested with the latter, but it runs itemFromCSLJSON() implicitly, so both translators should be okay.

More soon-ish ...

**Comment by fbennett** [comment]
Try the current [beta16](https://github.com/Juris-M/zotero/releases/tag/v4.0.29.6m64beta) and see how it goes. Should be a bit closer.

**Comment by retorquere** [comment]
I don't think Zotero-RDF will get to the point that I'll trust it to populate the DB for tests, but I'll take the occasional stab at it. The BBT debug translator simply dumps/loads the JSON all translators are handled, so it's easier to trust that.

One more test passes now, but given that Juris-M moves things from the extra field to dedicated fields, some tests (currently) fail predictably. There's things I can do to make some of those tests pass (just testing for extra fields, no biggie), but I would still need a way to be able to populate the database to start the tests, including putting stuff in the extra fields. I'd either have to do that manually (which is a possibility), but how invasive would it be to have a configOption to allow a translator to flag itself as exempt from the extra-field stripping? Or not even exempt but to leave the data there?

**Comment by fbennett** [comment]
Yeah, the Zotero RDF fix is more for satisfaction at this end (and for a colleague up the hall who needs it). Re a translator option, do you mean like having a toggle for use in testing that makes Juris-M perform imports without extracting from the Extra field?

**Comment by retorquere** [comment]
That would one option I could work with, sure; I could have the test runner detect BBT debug import and toggle that preference around the imports.

My ideal to be honest would be that I could have a configOption in the translator header to steer this behavior; I'd really preferably keep everything exactly the same except that I need a way to populate the DB without interference. I can of course have the test suite create items the way a user would normally through the UI, it's just that with Zotero it has been a safe assumption I could populate through a translator (which is heaps easier for me -- not necessarily for you)

**Comment by retorquere** [comment]
How do the Juris-M tests populate the DB?

**Comment by retorquere** [comment]
beta16 still strips out `{:original-date: XXXX}` and doesn't leave the value in any field available to the translators.

**Comment by retorquere** [comment]
Come to think of it: forget about exceptions for parsing out vars from the extra field. That's actually great, as long as I can find the resulting data in a reference field in the translator.

**Comment by fbennett** [comment]
Thinking things through a bit, I'm wondering whether this parsing-out-to-native-field thing is actually a good idea. It's good to have the code done, because eventually these extras will be merged into native Zotero; but if a translator makes use of original-date (say), and if it's used in Juris-M to add items to a group shared with Zotero users, only Juris-M will be able to make use of the field.

So (after having gone swings and roundabouts) it's probably better all around to disable that behaviour completely, at least for the present, and leave that stuff in Extra.

The Mozilla signing facility has been down for the past 12 hours, so I can't release a beta with this change yet. But I'm leaning in that direction.

**Comment by retorquere** [comment]
Urgh yeah I know. They think they've found the problem but nobody is giving me an ETA for signing being available again.

**Comment by fbennett** [comment]
It's almost as if they're happy we're leaving, but don't quite trust that we will actually jump.

**Comment by retorquere** [comment]
amen to that. I've been biting my tongue not to scream at them DON'T YOU MORONS TEST?! I DIDN'T WANT TO _&#(_&#(_& BE HERE, AT LEAST MAKE SURE I *CAN_ BE HERE IF I MUST ARGH ARGH ARGH ARGH. 

But I finally have my ETA. "Somewhere today".

Sad to see Mozilla slide that way. I haven't used Firefox for anything but Zotero for years, but I had some sympathy for them, and I actually liked working with XUL better than I like working with Electron. XUL going the way of the dodo is both an understandable choice and the last distinguishing feature they had, so I don't see them surviving in the mid term. If you want open source, there's Vivaldi, Chromium, probably others.

**Comment by retorquere** [comment]
Signing is back online.

**Comment by retorquere** [comment]
BTW, what happens if a Juris-M user enters the origdate into the appropriate Juris-M field (so no extra hacks) and then syncs with Zotero?

**Comment by fbennett** [comment]
At sync it's set in the Extra field in a patch encoded in JSON:

https://www.zotero.org/groups/japanese_judgments_and_rulings/items/itemKey/SNQVWZTN

**Comment by retorquere** [comment]
So the stripping isn't lossy even at sync, it's just that Zotero extensions must become Juris-M-savvy.

Either way works for me. As long as I can get the data.

**Comment by fbennett** [comment]
After wavering back and forth, I've decided to retain the conversion of hack fields on translator input. With it, we can use the same translator for the main legal types (which require a value in the non-Zotero Jurisdiction field), and get working Juris-M records. That's a bigger win than avoiding the narrow edge case I described above, so keeping the behaviour is worth the candle.

If you run into any further glitches, let me know - this round of fixes has been very beneficial, and I appreciate the time you've put into it.

**Comment by retorquere** [comment]
I can work with that, but beta16 still strips out `{:original-date: XXXX}` and doesn't leave the value in any field available to the translators, so the import is lossy from the pov if an export translator.

**Comment by fbennett** [comment]
It was fixed after, but we ran into the Mozilla signing thing. The service is back up, and I've released the changes made during testing; beta18 should be good.

**Comment by retorquere** [comment]
## Access date

A reference with accessDate: "2014-10-02 00:07:46" yields

```
"accessed": { "raw": "2014-10-02T00:07:46Z" }
```

rather than what Zotero exports:

```
"accessed": { "date-parts": [ [ "2014", 10, 2 ] ] }
```

Is that because it includes the time? 

## Editor in extra

`{:editor: Xxx}` in the extra field gives me a two-part name instead of (what I had assumed would be returned) a one-part name.

**Comment by fbennett** [comment]
Juris-M will currently export all dates as "raw" in CSLJSON (I think), because by default the client is configured to let the processor handle date parsing from the dumb string. That was done a long time ago, to enable proper date ranges. If the plugin option `extensions.zotero.hackUseCiteprocJsDateParser` is set to `false`, you should get what Zotero delivers (in theory, at least).

The parse of `editor` from the hack syntax needs fixing. I'll try to get that done this evening or tomorrow morning.

**Comment by retorquere** [comment]
Cool. I now just detect whether I'm getting a T00:00:00.\* date and parse that out myself -- The CSL-JSON I output is mainly for Pandoc, and it isn't hip with raw dates I think.

The single-part name is currently the only test that doesn't pass. I'm setting compatibility to v4.0.29.7 or later.

**Comment by fbennett** [comment]
The date parser is in Juris-M also, so could sent dates in the array
format. Seems better to play nice with other processors.

**Comment by retorquere** [comment]
The current implementation should be robust given either input.

**Comment by retorquere** [comment]
One more issue found: `{:editor: Xxx}` imports to an `author` field rather than an `series editor` for `report` references.

**Comment by fbennett** [comment]
The `editor` field is not valid on `report`, so a fallback to `author` would be normal. Zotero should (theoretically) do the same. `seriesEditor` maps to `collection-editor`, and that should reverse-map to the `seriesEditor` field okay.

**Comment by retorquere** [comment]
I will need to vary the test cases for Juris-M in any case, as BBT (at least currently) behaves differently depending on whether you have fields in Zotero fields or as customs in the extra field. I might change that at some point, but I'm close to having the tests go all green.

It's not a Zotero fallback, really, it's mine. I'm going to leave that as-is for now, as specifying vars in the extra fields is something the user does and can correct; I agree with you that your fallback is better though.

**Comment by fbennett** [comment]
Ah, right, of course - Zotero doesn't do this messiness. Should have a fix for two-field/one-field name modes soon.

**Comment by retorquere** [comment]
If Zotero would do this, the behavior would be unified across exporters/importers, and all would benefit at once.

Or better yet, if we'd _finally_ have extension-specific reference fields, we could do away with this hack completely.

**Comment by fbennett** [comment]
I think Dan doesn't like  the syntax (which to be fair I just kind of pulled out of the air one day). He prefers colon-separated key:val pairs delimited by newlines. One day we'll figure out how to get everyone's data on the same page, so to speak.

**Comment by fbennett** [comment]
I do think that custom fields of some sort will be coming after we're past the 5.0 rapids. The Zotero test suite is going to make things so much more flexible.

**Comment by retorquere** [comment]
Can you try https://github.com/retorquere/zotero-better-bibtex/releases/download/builds/zotero-better-bibtex-1.6.45-circle-2251.xpi and submit a debug report?

**Comment by retorquere** [comment]
Sorry, not for you, multitasking

**Comment by fbennett** [comment]
I've bumped the betas one patch number, in anticipation of an upcoming Zotero release (necessitated by a processor bug that I let sneak in):

[https://github.com/Juris-M/zotero/releases/tag/v4.0.29.8m64beta](https://github.com/Juris-M/zotero/releases/tag/v4.0.29.8m64beta)

Beta19 at that address should keep single-field names as single-field names.

**Comment by retorquere** [comment]
So is the next release going to be 4.0.29.8 then?

Are there serious movements towards the 5.0 release? Perhaps I should finally try to make BBT compatible. Not looking forward to it TBH -- I hate the promises approach, necessary evil as it may or may not be.

**Comment by fbennett** [comment]
I think it will be 4.0.29.7, actually - I thought there had been a 7
release already, but current is 6. Faulty memory.

I don't know how close the dev beta of 5.0 is. I'll be putting off the
Juris-M migration to the summer. But I did Juris-M patches for an earlier
version at Christmas-time, and actually found working with Bluebird a
pleasant experience.

**Comment by retorquere** [comment]
OK, updated.

I reckon I'm just reactionary -- I like sync code. No doubt that bluebird is one of the best in its field, but it's a field I had hoped to avoid altogether. It doesn't help that promisified code usually makes liberal use of constructs like

```
.then(function() {
  ...
})
```

which are in practice impossible to monkey-patch, and a good chunk of BBT behavior relies on monkey-patching.

**Comment by retorquere** [comment]
Well now -- one of the failing tests on Juris-M should in fact have failed on Zotero! I found a bug!

**Comment by retorquere** [comment]
Boom -- all green!

**Comment by retorquere** [comment]
Do you have an idea on when you are going to release .7? I'd rather not hard-wire my running tests to fetch a beta as I do now, but if I don't, my builds will start failing.

**Comment by retorquere** [comment]
For some odd reason, Juris-M seems [faster](https://circleci.com/gh/retorquere/zotero-better-bibtex/2256#build-timing) than Zotero. Could just be a fluke.

**Comment by retorquere** [comment]
Hi Frank,

I'm ready to cut a new release also for other issues I've fixed. Can you give me an approximate idea for a release date of .7? If it's very soon, I'll hold off and include Juris-M support, if not, it'll come in a later release.

**Comment by fbennett** [comment]
Should be all set.

Apparently I did guess the next Z version right. 4.0.29.8 was released
yesterday.

A parallel release of Juris-M that incorporates recent changes is up, as
4.0.29.8m65. I'll make up the Standalone releases for it today (w/in the
next 24 hours).

Frank
On Apr 18, 2016 22:25, "retorquere" notifications@github.com wrote:

Hi Frank,

I'm ready to cut a new release also for other issues I've fixed. Can you
give me an approximate idea for a release date of .7? If it's very soon,
I'll hold off and include Juris-M support, if not, it'll come in a later
release.

**Comment by retorquere** [comment]
Superb. My build has just started picking it up, once that goes green (and it should), I'm going to merge to master and cut a release.

Super thanks!

**Comment by retorquere** [comment]
Everything is go and BBT is out. Thanks for your help.

I'm going to hold off on reaching out to the Plus group from Alan Feldman... nothing against him at all, but I just had a rather nasty rebuttal from the MIT librarians about "plugging" updates to Better BibTeX, and they were already referencing BBT. I'm much better at responding to people that already have an interest.

**Comment by retorquere** [comment]
BTW, the speed diff between Zotero and Juris-M seems [pretty structural](https://circleci.com/gh/retorquere/zotero-better-bibtex/2326#build-timing), at least on the parts my tests are hitting (containers 2 & 3 are the tests for Juris-M).

**Comment by fbennett** [comment]
Not sure how to interpret the numbers, sorry - Juris-M is significantly slower? There shouldn't be any thrashing in there, but I'm less skilled than the original designers, and I've always assumed that what I've added drags things a bit.

**Comment by retorquere** [comment]
On the contrary -- Juris-M is faster. Those bars are just how long each test set takes to run; I've split my tests by hand between 0+1 for Zotero, and the same split for Juris-M in 2+3. Only the long bars in the middle matter, the rest is container setup and teardown, nothing to do with Zotero or Juris-M.

**Comment by retorquere** [comment]
If there is no "main" in the creator, can I assume it to be the "language" field?
