### ISSUE TITLE
dateparser: convertDateObjectToArray returns strings instead of numbers

### ISSUE THREAD

**Issue by retorquere** [Juris-M/zotero#2]
From my admittedly shallow understanding of the CSL docs, shouldn't https://github.com/Juris-M/zotero/blob/jurism/chrome/content/zotero/xpcom/dateparser.js#L285 convert the date parts to numbers? It now returns strings in my tests.

**Comment by fbennett** [comment]
It took me awhile to get there, but this is now fixed.

Note that Juris-M now uses the [citeproc-js date parsing module](https://bitbucket.org/fbennett/citeproc-js/src/tip/src/util_dateparser.js?at=default&fileviewer=file-view-default) directly.
