### ISSUE TITLE
Some CSL-vars in the extra field are deleted

### ISSUE THREAD

**Issue by retorquere** [Juris-M/zotero#24]
If I import a reference that has the following in the `extra` field, the information is removed from the extra field after import but not available in any field when I try to re-export them:

```
{:original-date: 1929}
{:original-title: Vom Wesen und Wert der Demokratie}
{:original-publisher-place: Tübingen}
{:original-publisher: J.C.B. Mohr}
```

fields such as

```
{:volume-title: ....}
```

are correctly imported into a field called `volumeTitle`. This must be new behavior in v4.0.29.12m97 final -- when I run the BBT test suite on jurism-v4.0.29.12m95, it passes.

**Comment by fbennett** [comment]
The way it works in the current version is that the item is read and dereferenced (so that the processor and Zotero copies of the item data can diverge) each time the item is processed. Any "cheater syntax" fields will be mapped into the CSL data internally, and removed from the "note" variable. That way, the "note" variable can still be used in annotated citation styles.

If you are reading the CSL JSON structure out of the processor, and then import the structure into Zotero, the data for those fields will indeed disappear.

I suppose the processor could do this in two stages, firstly parsing the item.note field on arrival to set the values as item fields, and secondly dereferencing the item.note content immediately before it is rendered, to strip out the data clutter.

It might take awhile, but I'll plan to move in that direction unless someone sees a problem with it. Meanwhile, if I've misunderstood the issue, let me know.

**Comment by retorquere** [comment]
I think I'm experiencing something slightly different. One of my import translators offers the following object to Juris-M:

```
var item = new Zotero.Item();
item.itemType = "book";
item.place = "København";
item.publisher = "Akademisk Forlag";
item.date = "2008";
item.extra = "{:volume-title: ThisVolumeTitle}\n{:original-date: 2005}\n{:original-publisher: origpublisher}\n{:original-publisher-place: origlocation}\n{:original-title: origtitle}";
item.title = "En ny sociologi for et nyt samfund. Introduktion til Aktør-Netværk-Teori";
item.shortTitle = "En ny sociologi";
item.language = "dan";
item.creators = [ { creatorType: "author", firstName: "Bruno", lastName: "Latour", fieldMode: "" };
item.complete();
```

After I do this, the `{:...}` data in the extra field seems irrevocably lost, except the `volume-title`; the volume title is visible in the Juris-M UI, and I find it in the `volumeTitle` field in an export translator, but the other fields I don't see in the Juris-M UI, and the data they contained is not available to an export translator. This data doesn't go through the CSL processor in this workflow (I would think).

**Comment by fbennett** [comment]
Okay, got it, I think. So it's a Juris-M specific issue.

Not sure of the exact cause (commuting now), but I'll try to look at it soon.

**Comment by retorquere** [comment]
Oh, yes, Juris-M specific. Zotero doesn't do it, and it's new to m97 -- m95 doesn't do this.

**Comment by fbennett** [comment]
This was a careless misstep. The original signature of the parsing function accepted an optional argument to flag CSL fields that can be mapped to the item type. I forgot what it was there for, and rewrote the function without it. Boom.

I've put up a Juris-M beta (<a href="https://github.com/Juris-M/zotero/releases/tag/v4.0.29.12m98beta">m98beta</a>) that restores the old behaviour, with a little extra.

The original braced-entry "cheater syntax" has received very poor reviews, and Zotero adopted the line-entry syntax for some of their content. This revision follows their lead, accepting both syntaxes in the processor, and normalizing to line-entry syntax for newly translated items. Will look forward to seeing how it pans out in your testing.

**Comment by fbennett** [comment]
Ah. There isn't a link to the processor documentation on braced-entry and line-entry syntax in this thread, so just in case, here is a <a href="http://citeproc-js.readthedocs.io/en/latest/csl-json/markup.html#cheater-syntax-for-odd-fields">link to the relevant section of the manual</a>.

**Comment by retorquere** [comment]
m98 passes all my tests.

**Comment by retorquere** [comment]
So the Zotero-preferred syntax is now the preferred syntax for citeproc too? Should I just start phasing out the other syntax? BBT treats both the same in any case, and always only picks up known CSL vars (taken from [here](http://docs.citationstyles.org/en/stable/specification.html#appendix-iv-variables)) and a few Zotero-specific additions (LCCN/MR/Zbl/arXiv/JSTOR/HDL/GoogleBooksID)

**Comment by fbennett** [comment]
Good to hear -- I'll bundle it in a proper release. Another processor change is in review, I'll wait until we have word on that, so it might take a few days. On preferred syntax, anything running upcoming processor tag 1.1.137 or higher (so I assume the next release of Zotero) will support both syntaxes. Braced-entry syntax will still be lurking around in legacy data, so best not to drop support for it yet.

**Comment by retorquere** [comment]
Could I receive notification (here or elsewhere) when the new release drops?I'm going to hard-code m98 in my test suite for now, but I will want to revert to "latest release" for testing when possible again.

**Comment by fbennett** [comment]
Yep, sure thing.

**Comment by retorquere** [comment]
BTW, `resource/config.js` only reports `v4.0.29.12` rather than `v4.0.29.12m...`, so I can't distinguish between these versions without looking up the installed addons list -- which doesn't work in standalone, so I fall back to ZOTERO_CONFIG.VERSION, but then I conclude that BBT is incompatible (because I test for `12m98` or greater).

**Comment by fbennett** [comment]
D'oh.

**Comment by retorquere** [comment]
Hi Frank, any news on a release date for m98? Since my test suite fails on m97, my release process blocks. I have my tests pinned to m98beta2 right now, but that means users must install m98beta2 in order to run the BBT release version.

**Comment by retorquere** [comment]
Hi Frank, I'm deeply sorry to bother you again, but this is becoming a pressing matter for me. People have started to upgrade to m97 and I have no supported version for them.

**Comment by retorquere** [comment]
Do you also plan to release m98 as standalone? Juris-M standalone is currently still at m95.

**Comment by fbennett** [comment]
Sorry. Will be out today.

**Comment by retorquere** [comment]
I see m98 dropped, thanks for that. Is standalone also going to be updated? Or is that going to stay at m95?

**Comment by fbennett** [comment]
Hi! Yes, I went in to work yesterday (Saturday) and did the build (at
last!). Standalone should also be at m98.

**Comment by retorquere** [comment]
The builds aren't automated? Can I help get that done?

**Comment by fbennett** [comment]
I use a VM for the Windows and Mac builds. To simplify things in the
script, they pull XPI for Juris-M and other plugins off the Web. Then the
bundles are uploaded to a Standalone release that I create manually against
a tag in the (otherwise unchanging) project.

I don't know whether scripting across VMs (or cross-compiling) is possible,
but it's probably not worth the effort, since Z Standalone itself has a
limited life expectancy.

**Comment by retorquere** [comment]
The manually part is tricky, but all the rest ought to be possible in a CI build given that you already have build scripts. There are a few services that do all three platforms. 

Why are the standalones deemed limited lifetime? Zotero is going to deprecate the full-featured plugin in favor of standalone soon, by last account in January. I thought Juris-M tracked Zotero?

**Comment by fbennett** [comment]
Closing this, as the issues here seem to have been overtaken by events. Feel free to reopen if I'm mistaken.
