### ISSUE TITLE
Standalone reports "Zotero" as appName

### ISSUE THREAD

**Issue by retorquere** [Juris-M/zotero#28]
`Components.classes['@mozilla.org/xre/app-info;1'].getService(Components.interfaces.nsIXULAppInfo).name` yields `Zotero` rather than `Juris-M`.

**Comment by fbennett** [comment]
I had a go at changing the `Name` value in `application.ini` from Zotero to Jurism. It causes Jurism to start as a fresh install, losing the pointer to a custom install directory if one is set. This change should happen at some point, but I'll need to think carefully about how to avoid confusion among users when it goes in.

**Comment by fbennett** [comment]
Looking into this a little further, it seems that changing the Name attribute in `application.ini` would have other downsides as well. It seems to be used by some of the word processor plugins for inter-process communication, so a change in the value would require that I spin off custom versions of them, and keep up with maintenance of patches. I think we'll have to leave this as it is for now.
