### ISSUE TITLE
dateparser: convertDateObjectToArray doesn't return the modified object

### ISSUE THREAD

**Issue by retorquere** [Juris-M/zotero#3]
https://github.com/Juris-M/zotero/blob/jurism/chrome/content/zotero/xpcom/dateparser.js#L307 is missing a `return thedate` (I think). It is called by `parseDateToArray` causing that always return undefined.

**Comment by fbennett** [comment]
Fixed awhile ago, I think - closing issue now in the course of housecleaning.

Note that Juris-M now uses the [citeproc-js date parsing module](https://bitbucket.org/fbennett/citeproc-js/src/tip/src/util_dateparser.js?at=default&fileviewer=file-view-default) directly.
