### ISSUE TITLE
Standalone m98 reports bad version string?

### ISSUE THREAD

**Issue by drammock** [Juris-M/zotero#30]
I'm getting this message in the Better BibTeX settings pane:

> Better BibTeX has been disabled because it found Juris-M 4.0.29.12..98, but requires 4.0.29.12m95 or later.

Note the doubled periods in the version string between `12` and `98`.

cc @retorquere

**Comment by fbennett** [comment]
Thanks for the heads-up ... you're using one of the Linux standalone builds, I guess. There was a typo in the version string for those. I've put up fresh copies, try reinstalling and see if it works a bit better.

**Comment by drammock** [comment]
works now, thanks @fbennett
