### ISSUE TITLE
Zotero.Item.prototype.getField -- questions about "language" and "honorEmpty"

### ISSUE THREAD

**Issue by retorquere** [Juris-M/zotero#31]
For `Zotero.Item.prototype.getField`, how do I enumerate the languages available for a field (or reference), and what does `honorEmpty` do?

**Comment by fbennett** [comment]
The `honorEmpty` value controls whether an empty field is pre-populated with the headline value, or returns empty. To get a list of all languages configured on the system, you can call `Zotero.CachedLanguages.getLangTags()`. There are also methods to fetch the current settings, ping back if you need info on those, and I'll remind myself of how they work.

The configured languages live in memory, so it's a synchronous call. If the object is called before JM startup, it needs an asynchronous call to its `.init()` method to load the data.

**Comment by retorquere** [comment]
But it looks like it I don't pass anything, I get sensible values back.

**Comment by fbennett** [comment]
Looking back at this again, and looking at the source, I'm not sure in what the context of your question was. Do you mean the comment mention of `honorEntry` in `xpcom/multilingual/fields.js` (which is confusingly named `forceTop` in the actual signature of the function)?

**Comment by retorquere** [comment]
I don't recall either. Currently, Juris-M passes my tests, if anything related to multi lingual is broken (which it likely is), I'll just wait for user reports.

**Comment by fbennett** [comment]
k
