### ISSUE TITLE
"video recording" director exported as author in CSL-JSON

### ISSUE THREAD

**Issue by retorquere** [Juris-M/zotero#33]
![video-recording](https://user-images.githubusercontent.com/132108/30054702-37654e3a-922d-11e7-866a-5454274f5311.png)

When I export this reference I get

```
[
  {
    "type": "video",
    "multi": {
      "main": {},
      "_keys": {}
    },
    "title": "The one with the Princess Leia fantasy",
    "publisher": "Warner Home Video",
    "publisher-place": "US",
    "volume": "3",
    "dimensions": "22 min",
    "medium": "DVD",
    "event-place": "US",
    "archive-place": "US",
    "note": "bibtex: friends:leia:dvd\ncontainer-title: Friends\nnumber: 1\noriginal-publisher: NBC\noriginal-date: 1996-09-16",
    "language": "en-US",
    "author": [
      {
        "family": "Mancuso",
        "given": "Gail",
        "multi": {
          "_key": {}
        }
      }
    ],
    "issued": {
      "raw": "2003"
    }
  }
]
```

where I had expected `author` to be `director`.

What is the best way to get test source references your way BTW instead of a screenshot? I use a JSON dump of the (mostly untouched) internal state of the reference in the translator, but you can't import that without having BBT installed.

**Comment by fbennett** [comment]
If you have the references in Juris-M, a CSL-JSON export should work. Zotero RDF may also push everything across, but that's less well tested in Juris-M.

**Comment by fbennett** [comment]
I've imported the item (at last!), and the creator comes through in the client as "Director." That's nice, but of course it should be "director" in the CSL, to get the correct label with pluralization support. Needs to be fixed.

**Comment by fbennett** [comment]
CSL JSON export now forces `author` to `director` when exporting JM `videoRecording` type.

**Comment by fbennett** [comment]
(Further to the previous note, the fix is in master, and will appear in the next release when it eventually surfaces.)

**Comment by retorquere** [comment]
This is not yet in 5.0.42m18?

**Comment by retorquere** [comment]
NM, my tests were off.
