### ISSUE TITLE
missing update.xml file

### ISSUE THREAD

**Issue by duncdrum** [Juris-M/zotero#36]
checking for updates on macOS 10.13.3 results in. 
![screen shot 2018-01-25 at 15 37 51](https://user-images.githubusercontent.com/6205362/35393630-d05b05f8-01e5-11e8-83ea-4cf0d3666ba5.png)

there is the update.ini file in the standalone package, but shouldn't this kind of stuff go into `info.plist` on mac?

**Comment by duncdrum** [comment]
Happy to report that updating via Help > Check for updates works on macOS, even with SIP enabled

**Comment by fbennett** [comment]
Yay, it's nice when things work!
