### ISSUE TITLE
Importing references: itemType "report" does not accept "publisher" field

### ISSUE THREAD

**Issue by retorquere** [Juris-M/zotero#39]
When I import references into JM using BBT, I translate `institution` to `publisher`, but for `report` type references, JM doesn't import this value (Zotero does).

**Comment by fbennett** [comment]
This is an import with CSL-JSON?

**Comment by fbennett** [comment]
Ah. JM diverges in the mapping for that one. It's assigned to `authority` (same as `court`, `legislativeBody`, and `issuingAuthority`). It's done that way because in JM `report` might be issued by an agency, and we'll eventually have pulldown lists of agency names for specific jurisdictions. That's 'way down the road, but it's the reason behind that choice.

**Comment by retorquere** [comment]
Nope, this is with the the BBT BibTeX importer. So for JM, I assign `institution` to the `authority` field instead of the `publisher`? That I can do.

**Comment by fbennett** [comment]
That should do it. (In CSL-M processing, an `authority` name can be composed of subelements separated by field-separator char `|`, and a style can select which parts to render.)

**Comment by retorquere** [comment]
That I can also do.

**Comment by retorquere** [comment]
In my tests I check that fields I try to import are understood by JM/Z; for this I run the following query:

```
SELECT it.typeName, COALESCE(bf.fieldName, f.fieldName) as fieldName, CASE WHEN bf.fieldName IS NULL THEN NULL ELSE f.fieldName END as fieldAlias
FROM itemTypes it
JOIN itemTypeFields itf ON it.itemTypeID = itf.itemTypeID
JOIN fields f ON f.fieldID = itf.fieldID
LEFT JOIN baseFieldMappingsCombined bfmc ON it.itemTypeID = bfmc.itemTypeID AND f.fieldID = bfmc.fieldID
LEFT JOIN fields bf ON bf.fieldID = bfmc.baseFieldID
ORDER BY 1, 2
```
but this doesn't show the `authority` field (and it does show that `publisher` is a field in the `report` type); even this

```
echo '.dump' | sqlite3 ~/.BBTZ5TEST/jurism/jurism.sqlite | grep authority
```

doesn't show the `authority` field. Is the `authority` field special in some way? I can add it to the exception list but it'd be good to know.

**Comment by fbennett** [comment]
Sorry, I was thinking of the wrong layer. If the field names here are Zotero item field names, then you're after the base field mapping of the Institution field on report (as the SQL shows). Got that then.

So if you are starting with a BibTeX item, your importer converts that into some intermediate form, and then that is imported into Zotero by one of the shipped import translators? What is the shape of the first data object that hits Zotero/JM code, and what is its entry point?

**Comment by retorquere** [comment]
I create a `item = new Zotero.Item('report')`, and then set the import fields on them. Right before I call `item.complete()` on the item, a JSON dump of `item` looks like this:

```
{
  "itemType": "report",
  "creators": [
    {
      "creatorType": "author",
      "firstName": "Drew V.",
      "lastName": "McDermott"
    },
    {
      "creatorType": "author",
      "firstName": "Gerald J.",
      "lastName": "Sussman"
    }
  ],
  "notes": [],
  "tags": [],
  "seeAlso": [],
  "attachments": [],
  "multi": {
    "main": {},
    "_keys": {}
  },
  "itemID": "1",
  "date": "1972-05",
  "publisher": "MIT Artificial Intelligence Laboratory",
  "title": "The CONNIVER Reference Manual",
  "extra": "bibtex: McDermott:72"
}
```

all of this gets imported except the `publisher` field.

But I now see there's a difference between Zotero and Juris-M here: Zotero has `institution` as a alias for the basefield `publisher`, and JurisM just has a separate field `institution`. No problem.

**Comment by retorquere** [comment]
Yep, that did it. Test are running, but this should be the final bit for JM compatibility.

**Comment by retorquere** [comment]
All tests green.
