### ISSUE TITLE
Bug. Court field internationalisation. Drop down unavailable and text is red until moved off focus and return.

### ISSUE THREAD

**Issue by JohnLukeBentley** [Juris-M/zotero#41]
@fbennett 

To reproduce:

* {JurisM} Open.
* {Firefox} Surf to https://www.caselaw.nsw.gov.au/decision/5aa0cd43e4b087b8baa8759b
* {Firefox} Hit the firefox JurisM addin button to add a “Web Page” type entry to Juris M
* {JurisM} Change “Item Type” to “Case”.
* {JurisM} in the Court field enter “District Court of New South Wales”. Observe this is red text (indicating it is not found in the drop down box). Fine so far. But there are a few problems from there .. 
  + If you click on the drop down box to see what values are acceptable, this is not permitted; and
  + You can’t tab away from the field even if you delete your entry.
  + The field remains red until you move focus away from the JurisM application. Only when you return focus is the field accepted.
  + (Edit: If a non conforming court is entered, this is lost if you restart JurisM).

Evidently only US courts are available at the moment. But even if you supplied a full international list I’d suggest you’d want to facilitate the entry of non-complaint court names while also signalling it is non-compliant.

That may well be your intentions and I’m just catching you part way through implementing this.

As a separate matter, do you mind my (our) posting bug reports and feature requests here rather than on https://mail.law.nagoya-u.ac.jp/mailman/listinfo/jurism-support ?

**Comment by fbennett** [comment]
What is the version of your Juris-M client? The gitchiness of data entry into the Court field was resolved in v5.0.37m10. The behavior now is as you describe, but a non-registered value is saved when you hit Enter, and receives a yellow highlight to flag that it's not a known identifier.

Tab should advance to the next field, that's a bug.

There is pulldown data for courts in the US, China, Vietnam, New Zealand, and some of the international organizations. You can browse the coverage in the [Legal Resource Registry](https://fbennett.github.io/legal-resource-registry) pages.

There isn't data for Australia yet. Adding jurisdiction data to the system is cumbersome in the current GitHub-based environment, but we will begin work on new jurisdiction infrastructure from April, with funding from the Shuttleworth Foundation. If you would like to join a design discussion on the workflow and interface, your input would be very welcome.

Posts here and to the mailing lists will reach me, but the mailing lists are most useful for support requests. This is a better channel for technical issues. (The definition of what falls in which category is in your discretion!)

**Comment by JohnLukeBentley** [comment]
I'm on 5.0.37m10. 

> Tab should advance to the next field, that's a bug.

Thanks.

> The behavior now is as you describe, but a non-registered value is saved when you hit Enter, and receives a yellow highlight to flag that it's not a known identifier.

I see that behaviour now. I suppose the fix is just to make this behaviour the same for Enter or Tab.

So, currently, if I enter "District Court of New South Wales" (a non-registered value) and hit Enter I will see the Yellow highlight. If I restart JurisM this value is preserved.

However if I now, with my mouse, put my cursor in the Court field, then move focus to another app or field within JurisM, restarting JurisM will mean the entire value "District Court of New South Wales" is lost. 

Presumably your fix will be just to treat a loss of field focus event identically to a Enter or Tab keyboard event. Indeed triggering your code on a LostFocus event ("onblur" in javascript) should work whether you Enter, Tab, or Mouse away from the field.

> Posts here and to the mailing lists will reach me, but the mailing lists are most useful for support requests. This is a better channel for technical issues. (The definition of what falls in which category is in your discretion!)

Thanks.

> There isn't data for Australia yet. Adding jurisdiction data to the system is cumbersome in the current GitHub-based environment, but we will begin work on new jurisdiction infrastructure from April, with funding from the Shuttleworth Foundation. If you would like to join a design discussion on the workflow and interface, your input would be very welcome.

I see there's isn't data for Australia in the sense of no data available via JurisM. At  https://fbennett.github.io/legal-resource-registry/index.html I see "Jurisdictions marked with stripes are stubs that do not yet provide court lists" ... and Australia is one such Jurisdiction so marked.

But I also that you have the data for Australia in some kind of back-end holding pen. That is, from https://fbennett.github.io/legal-resource-registry/index.html if I click on the **Yellow** Australia node I'll get the excel spreadsheet with "District Court of New South Wales". So you've done a great deal of work already on this front.

Yes I may very well be able to make some contributions to the jurisdiction-updating "design discussion on the workflow and interface". Is that discussion to take place at https://github.com/fbennett/legal-resource-registry (or is it already taking place somewhere else)? ...

My initial thought is that I'm surprised this is not just an XML or JSON file on github against which pull requests (or direct edits on github) can be made. I mean I see the existence of the stub https://github.com/fbennett/legal-resource-registry/blob/master/data/courts/au/nsw/index.txt. But I suppose you are thinking of having some kind of front end to that stub that allows non-technical folk to update that sort of file.

**Comment by fbennett** [comment]
> I see that behaviour now. I suppose the fix is just to make this behaviour the same for Enter or Tab.

Yes, that needs to happen. Thanks for pointing out the potential for data loss. I'll be sure that is fixed when I deal with Tab etc.

> But I also that you have the data for Australia in some kind of back-end holding pen.

The back-story on that spreadsheet data is in the site docs. It comes from set of courts data that I scraped from a consultant's website, with his blessing. The data haven't been checked for currency or accuracy, which is why it's not included in the machine-readable export.

> My initial thought is that I'm surprised this is not just an XML or JSON file on github against which pull requests (or direct edits on github) can be made.

Line diffs are not very readable or informative for XML or JSON data. The structure of the data is rather delicate -- we need to make decisions about hierarchy that are sometimes not intuitively obvious, so editing (at present) by working with text files in a filesystem makes it easier to see what's going on and control the semantics. The nesting niceties also mean that exposing a single raw data object would almost certainly run afoul of corruption in PRs. Finally, there is a *lot* of data in there. The size of the current data set is between 21 and 37 megabytes, depending on how it is expressed -- and it will expand considerably. For the present, the source is expressed as a set of reStructuredText files (!) in the GitHub repo behind the web view, but we obviously want something a bit more accessible.

**Comment by JohnLukeBentley** [comment]
Thanks for that explanation, on the bug and jurisdiction data. Yes, on the jurisdiction data there'll be a bit to think through. 

A pending question ...
> Yes I may very well be able to make some contributions to the jurisdiction-updating "design discussion on the workflow and interface". Is that discussion to take place at https://github.com/fbennett/legal-resource-registry (or is it already taking place somewhere else)? ...

**Comment by fbennett** [comment]
Work will start April 1st, when a pair of grad students will be released
from other obligations.

**Comment by JohnLukeBentley** [comment]
So you've yet to decide an a forum for that future discussion?

**Comment by fbennett** [comment]
Haven't given it any thought, no. When I have the next meeting with the dev
team, we'll work out what sort of channel will work best for them.

**Comment by JohnLukeBentley** [comment]
Thanks!

**Comment by fbennett** [comment]
The headline bug has been fixed in 5.0.39m14.
