### ISSUE TITLE
zotero-standalone-build: dir_build directory not found

### ISSUE THREAD

**Issue by mvwestendorp** [Juris-M/zotero#46]
I encountered a small hickup in building Juris-M. 
The build instructions for jurism creates a folder 'jurism'  in `prompt> git clone --recursive https://github.com/Juris-M/zotero.git jurism` causing ` prompt> ./scripts/dir_build` in "Building the client into the staging directory" to not find the directory.

I think this could be fixed by cloning into folder named `zotero` or by changing line 35 of config.sh in the zotero-standalone-build repository. Both work for me. However, as I am new to Juris-M I don't know what is the preferred option.

**Comment by fbennett** [comment]
Yes, I have hit the same problem. The simplest thing will be for me to change the instructions, and just unpack into ./zotero. Changing the directory name was a silly change on my part.

**Comment by mvwestendorp** [comment]
Thank you!

**Comment by fbennett** [comment]
Made the change. The revised instructions will go live soon.
