### ISSUE TITLE
Zotero.Cite.getAbbreviation gone in 5.0.39m17?

### ISSUE THREAD

**Issue by retorquere** [Juris-M/zotero#47]
Is it possible that Zotero.Cite.getAbbreviation has disappeared in 5.0.39m17? I'm getting "Zotero.Cite.getAbbreviation is not a function" which I didn't use to on Juris-M and which I still don't in Zotero.

**Comment by fbennett** [comment]
Yes, it was removed. If that's breaking tests for you, I can give it a
placeholder. JM will never use that code, and the file was getting hard to
read for clutter.

**Comment by retorquere** [comment]
I can just detect its absence, but that means no more automatic journal abbreviation for Juris-M in BBT.

**Comment by retorquere** [comment]
Wait, how does Juris-M do citeproc journal abbrevs these days then?

**Comment by fbennett** [comment]
It's handled by a companion plugin that monkey-patch installs a function with the same signature on the processor. The plugin enables on-the-fly editing of abbreviations in the currently selected style.

**Comment by fbennett** [comment]
It might be working already in a running client. I'll install BBT and have a look.

**Comment by fbennett** [comment]
Seems I have 18,000 items in my libraries. This will take awhile ...

**Comment by retorquere** [comment]
Which companion is that? I can install plugins as part of my test suite. Does it make the same function available? What happens if I install it in Zotero?

**Comment by fbennett** [comment]
The plugin is at https://github.com/Juris-M/abbrevs-filter It's not compatible with Zotero 5.0. Abbrevs are stored in a database, so the matching data for items needs to be boosted into memory before items are sent to the processor (so that it can be accessed synchronously). That required async-ifying the calls that invoke the processor and slotting in some hooks here and there. I posted a query about possibly making modifications to Zotero, and there was no response, so I removed it from the list of Zotero plugins to avoid user confusion.

**Comment by fbennett** [comment]
Nearly there with citation key generation ...

**Comment by fbennett** [comment]
Citation key shows at the top of each entry. When I select and item, right-click, choose Export Item, and select Better BibTeX as output and attempt to save, I get an error "no citation key," with a dump of the CSL JSON object. I'll file a debug ID for it.

**Comment by retorquere** [comment]
Bulk generation of keys hits the database a lot, and that's slower than it used to be.

The plugin is compatible with the latest JM right? Or is it simply not yet ported to the 5.0 architecture? Is there a way for me to find out what the latest version is? Just the latest GH release?

**Comment by retorquere** [comment]
I welcome the debug ID, but it's quite likely that the logs will say "Zotero.Cite.getAbbreviation is not a function" :laughing: .

**Comment by fbennett** [comment]
Here's the ID: N7C477EC

This was without "Use Journal Abbreviation" selected. With that selected, input freezes after typing a few characters of the filename for saving, and I can't proceed further. The client and plugin stay up, I can close the pane and try again. In that case, under the hood it's complaining that it can't find an ID (I assume the ID of the item).

**Comment by fbennett** [comment]
The latest version is just HEAD of master. I've gotten lazy about release tags, since it's just bundled with the client now. It's compatible with JM. Porting to Zotero is not possible, since it relies on code hooks that are not present in Zotero.

**Comment by fbennett** [comment]
The N7C477EC run above was done after citation key generation had completed.

**Comment by fbennett** [comment]
If the error is only that `Zotero.Cite.getAbbreviation` is not found, I can just restore that code in the next release. I guess it will allow you to hook into the abbreviation list distributed with Zotero, and bypass the Abbreviation Filter altogether.

**Comment by fbennett** [comment]
Tying editable abbreviation lists into BBT is probably not something you want to do.

**Comment by fbennett** [comment]
I've put the function back in there, it will appear in the next release.

With luck, the next will be the first JM Standalone to support automatic client updates. Been reading up about GitHub releases, I think that's going to work out very well. Just a bit of scripting to do before giving it a whirl.

**Comment by retorquere** [comment]
I've considered it adding editable lists.

So there's two errors relating to the problem you're seeing:

1. `Zotero.Cite.getAbbreviation is not a function`, which causes that item to not get a citekey. The abbreviator is always called (and the value cached) -- whether the value is actually used is steered by the option.
2. During export, any ref exported that doesn't have a citekey will (deliberately, because this should not happen) error out the export.

If the function doesn't do anything, I could just as well just not call it, but your call. Either will fix the problem you're seeing.

Unrelatedly, there's an Error in the log that says "Overwriting translator with same filename 'BetterBibTeX JSON.js'". Seems to work though.

**Comment by fbennett** [comment]
Restoring the function in full gets things working. That will go into the next release. Sorry about that, I should have thought that through.

I need to look into those overwrite warnings. Not sure where that's coming from, but I've seen it before with other translators.

**Comment by retorquere** [comment]
No need to be sorry, BBT goes wide and far beyond the documented APIs. It's closer to abuse than use, and I haven't documented all the spots I hook into. There's no way you could have known.

**Comment by fbennett** [comment]
Still, clobbering a core function was reckless on my part. Karl's TexMacs facility could also be impacted.

(Separately, every time I look at LaTeX stuff, I wonder whether it would make sense to replace BibTeX with a wrapper around a CSL engine.)

**Comment by retorquere** [comment]
I've considered that too. I don't remember why now, but there were structural differences that made this difficult.

**Comment by retorquere** [comment]
Could it be that `citet`, `citep` and `citeauthor` have no direct equivalent in citeproc? Or is that just Zotero that doesn't support it?

**Comment by fbennett** [comment]
citeproc-js can render the author and date portions of an author-date citation separately, so it's technically possible. It also doesn't have a concept of page location, but that should be a fairly straightforward thing to add. Work in that line would be a big step, though, and bring with it a lot of support burden. Interesting idea, though, if someone eventually decides to go there.

**Comment by retorquere** [comment]
Ask me again in 4 years when I have the PhD behind me (one way or the other) :roll_eyes:.

**Comment by duncdrum** [comment]
While a CSL solution for Latex to replace BibTex would be amazing, I smell a huge can of worms. 

@fbennett you could run and install BBL as part of the test suite, to get an early warning system.

**Comment by fbennett** [comment]
Yep, it's one of those "would be happy to advise" proposals that have all learned to be wary of.

Adding BBT to tests is probably overkill. It's clear that completely removing  core Zotero code was the cause of breakage this time around.

**Comment by retorquere** [comment]
Any indication on when a new version would be available? My tests are currently failing on this, I need to decide whether to disable testing of Juris-M or whether to wait for the release.

**Comment by fbennett** [comment]
I can roll a release tonight. I've been waiting to see if there are further fixes to the integration layer from Zotero, but it seems quiet lately.

**Comment by fbennett** [comment]
... and they just put up the fix for the issue I was waiting on. Yay!

**Comment by fbennett** [comment]
Running out of gas this evening (predictably), but I should be able to get the releases out by around noon tomorrow (14 hours away).

**Comment by retorquere** [comment]
NP

**Comment by fbennett** [comment]
Slightly longer than the 14-hour promise. We have some errands to run here that will consume the morning, but it will be coming soon. I'm very close to a trial of the GitHub-based releases with automatic update support, so I want to give that a go.

**Comment by fbennett** [comment]
Going to beg one more day on the release. If you need to go forward without Juris-M on our upcoming release, do go ahead. I've just gotten a trial download to work using the new infrastructure -- redirection by a clone of the Zotero PHP resolver running on our University server, with assets drawn from GitHub, where they are maintained by a clone of the Zotero release mechanism. Knocking off for the evening here, but the prospects for getting automatic updates working tomorrow are good.

By way of show-and-tell, here are the first release assets that I finally got working tonight:

[https://github.com/Juris-M/assets/releases/tag/client%2Frelease%2F5.0.42m18](https://github.com/Juris-M/assets/releases/tag/client%2Frelease%2F5.0.42m18)

**Comment by retorquere** [comment]
Pff, it's Easter weekend. No worries.

**Comment by retorquere** [comment]
Why have the downloads on a separate repo though?

**Comment by fbennett** [comment]
No special reason, it just seemed to sit better semantically that way.

**Comment by retorquere** [comment]
Semantically?

Upside for me of the move to GH is that I no longer have to scrape the Juris-M website to find the latest version, I can just check https://github.com/Juris-M/assets/releases/latest.

**Comment by fbennett** [comment]
That will get you the full client build, but you need the core module only for testing, no? To get you that, I can add a tag to that repo (Juris-M/zotero) when a release is cut, which doesn't seem to be happening at the moment.

**Comment by retorquere** [comment]
I take it with core module you mean a XPI which I could install in an older FF? I always test against the full release that users would normally use, so that would be the full client build. I just grab https://github.com/Juris-M/assets/releases/latest and get the x86_64.tar.bz2 from it. My tests currently pass again on 5.0.42m18.

**Comment by fbennett** [comment]
I think calling /latest will still work in the new configuration, but I need to sort through things and be sure that is so. There will be a beta channel, but I think that will not impact /latest if it's filed as a prerelease. I'll need to check that updates etc work against the client with prereleases though. (Still getting my head around the moving parts of it all.)

In any case, it looks like you can always get the latest release for a given channel by omitting the version value in a call to the resolver, like this:

https://our.law.nagoya-u.ac.jp/jurism/dl?channel=release&platform=linux-x86_64

**Comment by retorquere** [comment]
Will that start the download, or give me the latest version? It just struck me that if you're going to host multiple kinds of assets on that one "assets" repo, https://github.com/Juris-M/assets/releases/latest won't work for me, as only a single "latest" release can exist on a repo, and I wouldn't know if it was the latest client or the latest something else. Prereleases are separate and don't impact that.

**Comment by fbennett** [comment]
The resolver will start the download, and it looks like a HEAD request just
throws a 404. Will you need the file, or just the version?

**Comment by retorquere** [comment]
Both, but it doesn't actually start the download, it redirects to the download, which serves both purposes for me as long as the first redirect (from `our.law.nagoya-u.ac.jp`) looks like `https://github.com/Juris-M/assets/releases/download/client/release/<version>/<filename>`.
