### ISSUE TITLE
New setup.exe deletes custom styles.

### ISSUE THREAD

**Issue by JohnLukeBentley** [Juris-M/zotero#48]
To reproduce.

* In JurisM\styles create a custom style (e.g. I copy "jm-indigobook.csl", modify it, and name the modified version "jlb-jm-indigobook.csl").
* Download a new setup.exe, e.g from https://juris-m.github.io/downloads/ download Jurism-for-windows-all-5.0.39m17_setup.exe
* Run Jurism-for-windows-all-5.0.39m17_setup.exe
* Observe that "jlb-jm-indigobook.csl" has been deleted from JurisM\styles

It's unlikely to matter but I use a custom directory location. That is, {Juris-M Standalone} > Edit > Preferences > |Advanced| > |Files and Folders| > -Data Directory Location- > Custom: C:\Users\John\Documents\CustomData\Direct\Live\JurisM.

**Comment by fbennett** [comment]
Did you change the title and ID of the style? The link to the Zotero step-by-step guide, linked from the [CSL project site](http://citationstyles.org/authors/#editing-styles), has some useful pointers, just in case.

**Comment by JohnLukeBentley** [comment]
Ah, thanks. By chance I knew to do those sort of things but I hadn't in my  "jlb-jm-indigobook.csl"

Indeed I had ... 

    <id>http://juris-m.github.io/styles/jm-indigobook</id>

... rather than ...

    <id>http://juris-m.github.io/styles/jlb-jm-indigobook</id>

I'd suggest we leave this thread open and I'll verify that id change fixes the issue during the next Juris-M upgrade.

**Comment by fbennett** [comment]
Sure. That will definitely fix it though.

**Comment by JohnLukeBentley** [comment]
When debugging an app I've often thought "That will definitely fix it" ... only for that assertion to turn out false.

:)

... it's always good to test one's assertions in software. 

But, I'm glad for your assurance.
