### ISSUE TITLE
parseDateToString only returns first date for a range

### ISSUE THREAD

**Issue by retorquere** [Juris-M/zotero#5]
`Zotero.DateParser.parseDateToString('2014-12-31/2015-01-01')` returns `2014-12-31`

**Comment by fbennett** [comment]
The comment on convertDateObjectToString() says:

```
// XXXX Should be extended when date ranges are supported in the DB.
```

Apparently the string is meant for digestion by the native Zotero date functions, which don't know about ranges. Around the time this was written, we were talking about adoption of EDTF as the standard format for dates, but this parser isn't a full-blown or even conformant EDTF parser, and I didn't want to supply just some arbitrary syntax. I didn't have an immediate need for string output, so I left it half-finished like this.

**Comment by retorquere** [comment]
Alright, I have a custom version in place.
