### ISSUE TITLE
MS Word. Abbrevs. button disabled on first open.

### ISSUE THREAD

**Issue by JohnLukeBentley** [Juris-M/zotero#50]
To reproduce:

* Ensure Juris-M  and MS Word are closed.
* Fire up: Firefox (with the JurisM Connector enabled); Juris-M; and MS Word.
* {MS Word}. Open a document with an existing citation. Insert cursor in an existing citation. [Zotero] menu > [Add/Edit Citation]
* Observe the red bordered citation entry box. Observe that the [Abbrevs.] button is **disabled**.
* Press Enter on the keyboard to close the red bordered citation entry box.
*  [Zotero] menu > [Add/Edit Citation] (again).
* Observe the red bordered citation entry box. Observe that the [Abbrevs.] button is **enabled**.

Edit 01:

On Windows 10 64 bit Pro. JurisM 5.0.39m17.

Edit 02:  Added as first step "Ensure Juris-M  and MS Word are closed."

**Comment by fbennett** [comment]
That is expected behavior at present; the button is disabled when the processor contains no citation data. Clicking the Refresh button before the citation dialog is first opened will wake up the button. I don't understand the Zotero integration code well enough to try to make data loading more aggressive.

**Comment by JohnLukeBentley** [comment]
Would you understand Zotero integration well enough to able to programmatically fire off an "Refresh" command? If so on citation dialog first open perhaps you (the dev) could fire a "refresh".

Otherwise:
* I'm grateful for the workaround "clicking the Refresh button before the citation dialog is first opened"; and
* We could leave this issue open for someone who'll step up in the future.

Edit: "Understanding" to "understand".

**Comment by fbennett** [comment]
It's not just about code. Some documents contain a lot of citations. Forcing a long delay at startup would not be a good experience. Nor would displaying a set of abbreviation options that is incomplete.
