### ISSUE TITLE
Create a JurisM schema for validation at https://validator.citationstyles.org/

### ISSUE THREAD

**Issue by JohnLukeBentley** [Juris-M/zotero#51]
... as above.

**Comment by fbennett** [comment]
The Juris-M style editor performs validation, and supports both CSL and CSL-M styles: https://juris-m.github.io/editor/

**Comment by JohnLukeBentley** [comment]
Whoops. That'll do ...

However, it's not currently working for me in FF 59.0.2 (64bit):

* "Author-Date".
* Source > File Upload. Selected a custom *csl file.
* Load with: Juris-M.
* Clicking on [Validate] does nothing.

Is this working at your end?

**Comment by fbennett** [comment]
Press "Load" first. Use "Validate" after edits to regenerate the drag-and-drop preview pane.

**Comment by JohnLukeBentley** [comment]
Breaking UI conventions again ;-)

Thanks, I can validate now. Sorry this was not a genuine issue.
