### ISSUE TITLE
our.law.nagoya-u.ac.jp (133.6.82.183) is down

### ISSUE THREAD

**Issue by retorquere** [Juris-M/zotero#53]
My tests are currently failing because I can't verify I have the latest version.

**Comment by retorquere** [comment]
I know nothing of your release setup of course, but why not use the GH infra? Download counters (which, admittedly, are rather limited on GH)?

**Comment by fbennett** [comment]
Automatic updates depend on a resolver. I use a modified version of
Zotero's own resolver. It's written in PHP and can't be run on GH. To get
an idea of the structures involved, you can view the release files directly
via https://github.com/juris-m/assets/releases

In theory, the resolver logic and underlying data could be shipped to the
browser and run there, but the code for it would need to be written and
tested. Not planning to do that.

It looks like Nginx suddenly got fussy about something in the config, and
refuses to start. Everything else is up and running so we'll be back in
business once I figure out what incantations it wants to see.

**Comment by fbennett** [comment]
It's back up now. Nginx doesn't like mixed nesting of string- and regex- style location specifiers. Didn't know that, but it looks like something on the VM must have been tweaked by the maintainers and made it fussy about it. A syntax adjustment, and all is well.

(Edit: and sorry for the inconvenience!)

**Comment by retorquere** [comment]
I managed to work around it; I was already caching downloads, so now I'm just falling back to the latest cached version.

Do client updates work differently than extension updates? I don't use a resolver.

**Comment by retorquere** [comment]
Something is still not right:

```
$ curl -v 'https://our.law.nagoya-u.ac.jp/jurism/dl?channel=release&platform=linux-x86_64'
[1] 23416
*   Trying 133.6.82.183...
* TCP_NODELAY set
[emile@titanarum better-bibtex (951 *)]$ * Connected to our.law.nagoya-u.ac.jp (133.6.82.183) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /home/emile/anaconda3/ssl/cacert.pem
  CApath: none
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* NPN, negotiated HTTP1.1
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Unknown (67):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: CN=our.law.nagoya-u.ac.jp
*  start date: Feb 18 10:33:30 2018 GMT
*  expire date: May 19 10:33:30 2018 GMT
*  subjectAltName: host "our.law.nagoya-u.ac.jp" matched cert's "our.law.nagoya-u.ac.jp"
*  issuer: C=US; O=Let's Encrypt; CN=Let's Encrypt Authority X3
*  SSL certificate verify ok.
> GET /jurism/dl?channel=release HTTP/1.1
> Host: our.law.nagoya-u.ac.jp
> User-Agent: curl/7.55.1
> Accept: */*
> 
< HTTP/1.1 404 Not Found
< Server: nginx/1.10.2
< Date: Sat, 14 Apr 2018 11:22:06 GMT
< Content-Type: text/html
< Content-Length: 169
< Connection: keep-alive
< 
<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.10.2</center>
</body>
</html>
* Connection #0 to host our.law.nagoya-u.ac.jp left intact
```

**Comment by duncdrum** [comment]
yes, while i see no errors, m28 does not show up from inside juris-m. (on macOS)

![screen shot 2018-04-14 at 13 25 37](https://user-images.githubusercontent.com/6205362/38767742-8129240c-3fe7-11e8-984f-d8c94dcf12ed.png)

**Comment by fbennett** [comment]
@retorquere Try now (but with the -L option to curl).

@duncdrum m28 is brewing. Linux done, Windows in progress, Mac to follow.

Sorry about the glitches in the update/download links. After getting our Nginx server configured and working with the PHP-based resolver via fastcgi, I must have tweaked the configuration with what I thought was an innocent change. The VPS rack at University must have been rebooted yesterday, and the server refused to start. That led to some more fumbling around on my part, to get the script running again under the correct addresses. I *think* it's sorted now, but if you hit any further trouble, post back.

The Windows build-and-deploy just finished. Mac coming up, should be done within the next 30 minutes.

This should bring Juris-M to a period of relative calm for a time, assuming no further issues arise from the work upstream on word processor integration.

**Comment by retorquere** [comment]
@fbennett I deliberately don't use -L because I use the Location header to detect the latest version number. It works again now, thanks.

**Comment by fbennett** [comment]
Got it. It was my typo: the server had been mis-re-configured to recognize
only /dl.php.

**Comment by fbennett** [comment]
All should be ticking over normally again.

**Comment by duncdrum** [comment]
confirmed

**Comment by duncdrum** [comment]
it s down again

**Comment by fbennett** [comment]
Thanks for the heads-up. I'll definitely get auto-restart set up tomorrow. Enough of this.

**Comment by fbennett** [comment]
Should be up again now.

**Comment by fbennett** [comment]
It's all Donald Trump's fault, but there is no point in complaining as he's President and everything. Tomorrow I will implement a workaround. Promise.

**Comment by duncdrum** [comment]
walls can't keep us out :) all green again

**Comment by fbennett** [comment]
"And the sons of Pullman Porters
And the sons of engineers
Ride their father's magic carpet made of steel..."

-- The immortal Steve Goodman

**Comment by aarontimo** [comment]
The connection to https://our.law.nagoya-u.ac.jp/ is pulling up a privacy error.

**Comment by fbennett** [comment]
Sorry about that! I need to fix this also - but I've renewed the cert for now, back to normal.

**Comment by aarontimo** [comment]
Thank you!
