### ISSUE TITLE
Download URL times out

### ISSUE THREAD

**Issue by retorquere** [Juris-M/zotero#55]
https://our.law.nagoya-u.ac.jp/jurism/dl?channel=release&platform=linux-x86_64 times out (which causes my tests to fail).

Time for a move to GH releases perhaps?

**Comment by retorquere** [comment]
Or stick it behind cloudflare?

**Comment by retorquere** [comment]
I am prepping for Ubuntu-packaging of Zotero, I could add Juris-M support, or should you how to do it yourself (turns out it's trivial).

**Comment by fbennett** [comment]
Sorry about that downtime. It was due to scheduled maintenance by our IT administration (they swapped in new servers or something), and I neglected to act on their mail by flagging the outage on the project page.

JM releases are already lodged on GitHub, but version selection (including delivery of binary diffs as required) is handled by a PHP script running on our own server. It's the same release infrastructure used by Zotero, tweaked to deliver JM via its GitHub release objects (and so ultimately from AWS channels used by GH...) instead. It requires the dynamic-y PHP script as glue to splice things together. Running that on a University server is probably the best approach available for the moment, despite this week's glitch.

**Comment by retorquere** [comment]
I'm looking at the [releases on this repo](https://github.com/Juris-M/zotero/releases) but there I see only the versions but no attached binaries. I had forgotten about the incremental updates, but I can't use them for my tests (juris-m installs are not retained across tests).

I've added [apt-gettable versions](https://github.com/retorquere/zotero_deb) of Juris-M to my repo. I'd be happy to keep this updated manually but it's not actually hard to do (my steps are on that same page) should you want this under your own control.

**Comment by retorquere** [comment]
Wait, I had forgotten about the [separate repo for assets](https://github.com/Juris-M/assets/releases) you had set up.

**Comment by retorquere** [comment]
Looking at how that's set up, it may be feasible to add a deb version there. Packaging a deb is really easy if you have the built client at hand, which you must have to upload the .tar.bz2's there.

**Comment by fbennett** [comment]
Yep, there's a ground-install bundle for each platform, including Linux. It
would be great to have a Linux installer! I'm not able to put time into it
at the moment, and probably until the hols, because teaching and because
writing. But it would be a great to have that available.

Frank

**Comment by retorquere** [comment]
OK so it turns out to be really, really easy. [This script](https://github.com/retorquere/zotero_deb/blob/master/update.py) automates the whole packaging process for. A good chunk of that script does download, unpack and version detection, which could go away if it were done during the Juris-M build. I host on SF not because it is great (it is not) but it does have the easiest deploy (just scp/rsync) and it can host apt repos (GH cannot).

**Comment by retorquere** [comment]
The full script in plain bash can be found at https://gist.github.com/c03ee2b29eae14a79472366806f406ad but it assumes you have a clean state (which is sensible for the jurism build).

**Comment by retorquere** [comment]
https://our.law.nagoya-u.ac.jp/jurism/dl?channel=release&platform=linux-x86_64 gives me a `502 bad gateway` error.

**Comment by fbennett** [comment]
Ouch, not again! I'll check this out today.

**Comment by cwittern** [comment]
Looks like this is not yet fixed, I still see the 502 error with
https://our.law.nagoya-u.ac.jp/jurism/dl?channel=release&platform=linux-x86_64

**Comment by retorquere** [comment]
You can fetch the latest version [here](https://github.com/Juris-M/assets/releases/latest).

**Comment by cwittern** [comment]
Ah, got it, thanks!
