### ISSUE TITLE
Make language settings for shorttitle independent from corresponding settings for titles

### ISSUE THREAD

**Issue by denismaier** [Juris-M/zotero#56]
At the moment, language settings for titles (orig, script, lang) affect also shorttitles. Yet, in some situations it might be that we want shorttitles to behave differently. For example: 
titles: "transliteration [orig]"
shortitles: "transliteration"
Would that be feasible?

**Comment by denismaier** [comment]
Any opinions about this?

**Comment by fbennett** [comment]
Sorry, I didn't pick up your original post. I'll float the issue on the [Jurism mailing lists](https://juris-m.github.io/support/) to see what people think - this is certainly possible, but it will be good to poll users, since other related tweak suggestions might turn up.

**Comment by denismaier** [comment]
Ok, good idea. Even better if this can be optimized even more.  We'll certainly need to discuss what a good behaviour would be like. It's just that the current behaviour is sometimes a bit odd. Like when you have the title field in the original language and in transliteration, but the shorttitle only in one variant => the full title field is used as a fallback.

**Comment by fbennett** [comment]
With cross-field inheritance in the latest releases, I think it's safe to close this. Feel free to reopen if that's overreaching.
