### ISSUE TITLE
Release tagging

### ISSUE THREAD

**Issue by retorquere** [Juris-M/zotero#57]
On which repo are releases tagged? I see the latest packaged release is 5.0.52m40, but the latest tag here is 5.0.42m21.

**Comment by fbennett** [comment]
The family of client releases lives at https://github.com/Juris-M/assets, but when putting together a change list last month, I realized that I've been lazy about tagging the core code. I didn't see an easy way to match past releases to their commits at this point. I'm close to a full release, with a second-round beta going out tomorrow. I'll be sure that and future releases are tagged in this repo.

**Comment by retorquere** [comment]
What does Juris-M do to check that a new version is available?

**Comment by fbennett** [comment]
It uses the Zotero resolver, adapted to Jurism. It's written in PHP, which I understand only vaguely. I think the client issues a call for "latest" or somesuch, and the resolver returns a patch or a full installer, depending.

**Comment by retorquere** [comment]
Do you know the URL it calls? For Zotero, https://www.zotero.org/download/client/manifests/release/updates-linux-x86_64.json is called.

**Comment by fbennett** [comment]
That file exists, on `our.law.nagoya-u.ac.jp`, but it's used internally by the PHP resolver. I don't think you can access it directly over the Web. What the client calls is this, with appropriate values:

https://our.law.nagoya-u.ac.jp/jurism/update.php/%VERSION%/%BUILD_ID%/%BUILD_TARGET%/%LOCALE%/%CHANNEL%/%OS_VERSION%/update.xml

If you're just needing the version tagging in the source to be done more reliably, I can try to be more careful about that.

**Comment by retorquere** [comment]
That's one option, but the client checks something to see that it needs to update right? That must be publicly available, I could just use the same mechanism.

**Comment by retorquere** [comment]
I don't use the tagging for zotero either, I call that url and that gets me the latest version.

**Comment by fbennett** [comment]
I'm pretty sure that the resolver returns only a link to the patches, but
when I have a chance I'll see if I can get a network trace out of the
client.

**Comment by retorquere** [comment]
Eh don't worry about it, I can read the partials list and take the last version.
