### ISSUE TITLE
RTL text fontsize in Word

### ISSUE THREAD

**Issue by denismaier** [Juris-M/zotero#58]
In Word footnotes, RTL text is bigger than the surrounding text (12 pt vs 10pt). In LibreOffice, it works as expected.

**Comment by fbennett** [comment]
We get the same fault in Word for Khmer and Lao scripts here. After fighting with it a couple of times, I have fallen back to just recommending to candidates that they use LibreOffice, which has configuration settings for composite fonts, and drop Word, which does not. (I'm not sure whether any have taken the advice.)

I would love to be proven wrong, but it seems like Word is just too broken to struggle with on this particular issue.

**Comment by fbennett** [comment]
One thing I should have mentioned above is that Zotero & Jurism don't specify any font-size settings in citation text that they generate. It's up to the word processor to do the right thing with what it receives.
