### ISSUE TITLE
dateparser: parseDateToObject seems to recognise underscores for ranges but drops start on the floor

### ISSUE THREAD

**Issue by retorquere** [Juris-M/zotero#6]
`Zotero.DateParser.parseDateToObject('1897_1913')` outputs `{ year: '1913' }`

**Comment by fbennett** [comment]
See my comment on #7.

**Comment by retorquere** [comment]
It surprised me a little since it correctly parses 1897/1913 into a range.

**Comment by retorquere** [comment]
What about something like `01/01/1989`? It currently returns `{ day: 1, year_end: '1989', day_end: 1, year: '1989' }`. I now understand the date parser isn't really intended for translators, but which part of Juris-M/citeproc does use it? I need to go find out to which extent my needs and those needs diverge.

**Comment by fbennett** [comment]
True, would probably be worth adding that to the mix, since the underscore is (apparently) a common way of working around the lack of date range support in Zotero.

**Comment by fbennett** [comment]
It's used to convert item dates to CSL JSON dates, for digestion by the processor.

**Comment by retorquere** [comment]
That's what I had supposed, but isn't `2004 [1929]` expected to turn up somewhere in the bibliography?

Is this at all the proper place to have these discussions BTW?

**Comment by fbennett** [comment]
> What about something like 01/01/1989? It currently returns { day: 1, year_end: '1989', day_end: 1, year: '1989' }.

That would be a bug.

**Comment by retorquere** [comment]
Same problem I think for 11/2012

**Comment by retorquere** [comment]
I've filed a new issue for those year-last dates.

**Comment by fbennett** [comment]
This has been fixed to recognize the underscore workaround as a date range delimiter.

Note that Juris-M now uses the [citeproc-js date parsing module](https://bitbucket.org/fbennett/citeproc-js/src/tip/src/util_dateparser.js?at=default&fileviewer=file-view-default) directly.
