### ISSUE TITLE
Allow for multiple transliteration variants

### ISSUE THREAD

**Issue by denismaier** [Juris-M/zotero#61]
In certain disciplines, transliteration requirements may vary depending on citation style requirements, journal, publisher, etc. Right now, this means that the field with the transliteration must be edited. Is there a way to add additional (possibly arbitrary) transliteration variants?

**Comment by fbennett** [comment]
The menu-driven language variant mechanism in Jurism is based on [BCP 47](https://tools.ietf.org/html/bcp47), which is ridiculously fine-grained and flexible.

**Comment by denismaier** [comment]
Yes, indeed, but can I select Hebrew transliteration according to Brill,
Encyclopedia of Jewish History and Culture, etc.?

Frank Bennett <notifications@github.com> schrieb am Di., 9. Apr. 2019,
14:44:

**Comment by denismaier** [comment]
Some scholars might find these "inofficial" publisher variants more
relevant than official variants like the loc rules.

Denis Maier <maier.de@gmail.com> schrieb am Di., 9. Apr. 2019, 14:56:

**Comment by fbennett** [comment]
Not in the current client, but I haven't updated the data set in awhile. If desired variants are missing from the current list, you would need to make a proposal to the standards group at ietf-languages@iana.org, with the details of the "Language Subtag Registration Form" laid out in the BCP 47 specification. Once adopted, it can be pulled in and included in the Jurism lists.

**Comment by fbennett** [comment]
It doesn't need to be official in any officious sense, it just needs to be well defined, stable, and in reasonably wide use within a community. The subtag registry even includes things like "Boontling," a slang once used by young people in a small California community to talk about forbidden topics in front of their elders ...

**Comment by fbennett** [comment]
So as far as Jurism is concerned, it's a problem solved. You would need to work things out with the IETF working group.
