### ISSUE TITLE
Improved support for Swiss courts

### ISSUE THREAD

**Issue by denismaier** [Juris-M/zotero#62]
What would be needed for an improved Swiss legislation support? The kind of support for the US, Poland, France, Austria, and Czech Republic that has been added in the latest betas.

**Comment by fbennett** [comment]
The build infrastructure for support is still kind of DIY, but the steps are clear now. There are three things. First is a JSON list of courts and jurisdictions, organized like this (some content omitted for brevity):
```
{
    "courts": {
        "sc": {
            "name": "Nejvyšší soud",
            "en": "Supreme Court"
        },
        "hc": {
            "name": "Vrchní soud",
            "en": "High Court"
        },
       ...
    },
    "jurisdictions": [
        {
            "path": "cz",
            "name": "Czech Republic",
            "courts": ["sc", "sac", "cc"]
        },
        {
            "path": "cz/olomouc",
            "name": "v Olomouci",
            "en": "Olomouc",
            "courts": ["hc"]
        },
        {
            "path": "cz/praha",
            "name": "v Praze",
            "en": "Praha",
            "courts": ["hc"]
        },
        ...
}
```
Coverage should only extend down to the jurisdiction of frequently-cited courts. For less-cited courts, users can enter a custom court name in the Court field, which is okay for occasional items where rigid consistency is less important.

I use the JSON info file to push text files into the <a href="https://github.com/fbennett/legal-resource-registry/tree/master/data/courts">LRR repository</a> (you don't want to work with the data in that form directly, it's too fragile) ... then there is a script that rips the data from the LRR, and ... builds a compact JSON object that ... Jurism uses to build an SQL database ... that is used in the Jurism UI to drive the Jurisdiction and Court fields. (>whew<)

So the JSON info file gets us jurisdiction and court identifiers. The other thing needed is sample citations, which are usually pretty simple for civil jurisdictions. As the court identifiers are sent to the processor verbatim in CSL JSON, each jurisdiction+court needs a specific "abbreviation" to produce the correct form of its name (which may include the jurisdiction name) in citations. To generate those values, courts and jurisdictions below top-level should have values set on them (under some key or other) that can be combined in a uniform way to produce the correct name. In the Czechia data, for example, the High Court in Prague is courts.hc.name + jurisdictions[n].name, or  "Vrchní soud v Praze".

In sum, if I you can produce a JSON data file like that above, the machine can add similar Switzerland support with relatively little effort. (Oh - that plus a set of sample citations for the various courts)

**Comment by fbennett** [comment]
A beta release that allows manipulation of jurisdictions and court abbreviations without rebuilding the client, will be out soon, probably tomorrow. Once it's up, I'll document the support tools that it's based on, and we'll be off to the races for worldwide jurisdiction support. Scalability issues, here we come!

**Comment by fbennett** [comment]
The format of files in the [Legal Resource Registry](https://github.com/juris-m/legal-resource-registry) (which is included in the client source repo under ``juris-desc``) has been updated and documented. The new format places everything related to jurisdiction support in the ``desc`` files, with enough flexibility to cover any combination of jurisdiction structures and language variants.
