### ISSUE TITLE
Interface issues / moving lines

### ISSUE THREAD

**Issue by denismaier** [Juris-M/zotero#63]
I don't know if this is a Zotero or a Juris-M or a Linux issue, but this here occurs on my Linux machine with Juris-M: When I move from one field to the next it seems that the fields are not set on a fixed location, but the currently selected lines moves a bit up or down. After jumping to the next field, the last one gets back into place.

**Comment by denismaier** [comment]
Ok. Looks like a Linux issue. I cannot reproduce this on a fresh installation on Windows 10.

**Comment by fbennett** [comment]
Jurism will (mostly) follow Zotero's behavior in the UI. Zotero aim to rewrite the entire interface in React, so we can wait an see if minor glitches persist after that watershed.
