### ISSUE TITLE
Can we use main/subtitle-splits already with Juris-M?

### ISSUE THREAD

**Issue by denismaier** [Juris-M/zotero#64]
You mentioned [here](https://discourse.citationstyles.org/t/handling-main-sub-title-splits-citeproc-js/1563) that citeproc-js is already capable of splitting the `title` variable into virtual variables `title-main` and `title-sub`.

Can we already use this feature with Juris-M?

**Comment by fbennett** [comment]
Not yet, but the variable names validate under the CSL-M schema, and I'll turn on splitting in the next release. (A beta should be coming out tomorrow, with some important improvements to jurisdiction management.)

**Comment by denismaier** [comment]
Oh great! So, something like this will work?

```
<macro name="title-full">
  <group delimiter=". ">
    <text variable="ttitle-main">
    <text variable ="title-sub">
  </group>
</macro>
```

>

**Comment by fbennett** [comment]
It should do -- the split functionality was coded in long ago, after a
report about the use of periods by a German user; but the split initially
relied on a matching shortTitle value to hint at the break-point, and it
was too cumbersome to be widely advertised. We now have pretty-good
heuristics working from the title field alone, so things should mostly Just
Work in a style that makes use of the virtual variables.

Frank

**Comment by denismaier** [comment]
Ok. So this means we'll still be able to use the `shortTitle` for different purposes, like further abbreviating the title? We won't lose this feature? Would be great...

Anything special we should know about the heuristics? What if it breaks? Can we override the decisions, like escaping punctuation if need?

**Comment by fbennett** [comment]
There are some tests here:

https://github.com/Juris-M/citeproc-js/blob/master/fixtures/local/form_ContainerTitleShortWithTitleSubSupport.txt

I'm not sure about overrides, but if escaping proves necessary, we can work
something out.
