### ISSUE TITLE
Abbrevs Filter not working/won't load (Mac Juris-M 5.0.80m9)

### ISSUE THREAD

**Issue by radiationnow** [Juris-M/zotero#70]
On a fresh install of Juris-M on a MacOS Catalina machine, the abbrevs filter won't load data from any of the default sources (nor will it allow load from file).  Behavior is to simply do nothing in response to clicking import.  In addition, default abbreviations don't appear to be in use (e.g., for the JM Indigo Book style, "boston university law review" is not abbreviated at all.)

The error console contains the following errors that appear potentially relevant.  For import from default (appears on clicking import):

```
[JavaScript Error: "me is undefined" {file: "chrome://abbrevs-filter/content/xpcom/attachers.js" line 79)}]
```

For import from file (appears on clicking in the "Click here to select a file" field):
```
[JavaScript Error: "TypeError: fp.show is not a function" {file: "chrome://abbrevs-filter/content/dialog.js" line: 509})]
importChooseSourceFile@chrome://abbrevs-filter/content/dialog.js:509:12
onclick@chrome://abbrevs-filter/content/dialog.xul:1:1
domListener/attachStyleEngine/<@resouce://gre/modules/addons/XPIProvider.jsm -> file:///Applications/Jurism.app/Contents/Resources/extensions/abbrevs-filter@juris-m.github.io/bootstrap.js:156:6
```

**Comment by fbennett** [comment]
Thank you for reproducing this. I can reproduce the bug. I'll have a
release out soon to fix it (the version will be 5.0.81m3 or higher). More
soon.

**Comment by fbennett** [comment]
Found the bug. I need to jump to the daily commute now, but the 5.0.81m3 release will be out, with a fix for this within the day.

**Comment by fbennett** [comment]
The release is up. It will update automatically within 24 hours, or you can pull in the changes from "Help -> Check for updates" in the Jurism client.

**Comment by fbennett** [comment]
(Oh, wait - the Mac update hasn't quite reached GitHub. Will be there soon, though.)

**Comment by fbennett** [comment]
All set, should be ready now.

**Comment by radiationnow** [comment]
Can confirm that this fixes the issue, allowing import of default lists and abbreviating a test item properly.  Thanks for the quick fix!

**Comment by fbennett** [comment]
My pleasure, thanks again for calling attention to the bug!
