### ISSUE TITLE
Feature request: change language

### ISSUE THREAD

**Issue by galantra** [Juris-M/zotero#71]
https://www.zotero.org/support/supported_languages
Standard Zotero seems to have this option and Juris-M doesn't.

JurisM 5.0.81m4
Windows 10

**Comment by denismaier** [comment]
What exactly do you mean? I am not aware of language related features that are present in Zotero but lacking in Juris-M. It's usually the other way round.

**Comment by galantra** [comment]
Sorry, let me clarify: I mean specifically the language of the user interface. Right now, it is my system's language. I would like to change it to English. I haven't found an option to control the interface language.

**Comment by fbennett** [comment]
You should be able to force the UI language via Preferences -> Advanced.
Switching the UI language was formerly controlled in Jurism via the "Languages" preference panel, but that was removed with Zotero added language switching in the "Advanced" panel.

**Comment by galantra** [comment]
Thank you so much! I am going to pay higher attention to the instructions from now on and not rashly open an unclear issue.
Sorry for bothering you two.
