### ISSUE TITLE
Automatic PDF retrieval

### ISSUE THREAD

**Issue by galantra** [Juris-M/zotero#72]
https://github.com/zotero/zotero/commit/679a6d5cc7e6c87931ea3b484332dda168ad5b5d

I looked for this in the Juris-M code and didn't find it. Then I tried to change my Juris-M files accordingly but the structure is different.

Would it be a good feature to implement?

**Comment by fbennett** [comment]
Jurism is level with Zotero, and the feature should be included. A code block from that change was removed by Zotero a few days later by commit https://github.com/zotero/zotero/commit/03a15d47afdc70367387cf5c99c56a04350ac88a

**Comment by galantra** [comment]
Thanks, I hadn't seen that before.

I thought there was a "retrieve PDF" button somewhere. But it seems like the retrieval is a hidden process. For me, it has only retrieved tables of contents so far; even when I I added an item by DOI which had a publicly available full text PDF.

Anyway, I see that Juris-M is level with Zotero and I'm closing this.

**Comment by fbennett** [comment]
If you post a sample link, I can check it out to be sure.

**Comment by galantra** [comment]
Okay, I've done more testing and the rule seems to be that the function only works with DOIs and not with ISBNs. I didn't know that before.

This retrieves the PDF
* https://osf.io/preprints/lawarxiv/pr3ek/  
* 10.31228/osf.io/pr3ek
This, too:
* https://osf.io/preprints/lawarxiv/pr3ek/
* 10.31228/osf.io/pr3ek

This as well:
* https://openknowledge.worldbank.org/handle/10986/23533
* http://dx.doi.org/10.1080/15570274.2015.1075762

Here, only the DOI retrieves the PDF:
* https://openknowledge.worldbank.org/handle/10986/32436
* 978-1- 4648-1441-9
* 10.1596/978-1-4648-1440-2

Here, only the DOI retrieves the PDF. as expected, it doesn't retrieve the .epub or .mobi:
* http://www.carlgrossmann.com/?p=11914
* 10.24921/2020.94115939
* 978-3-941159-39-6
* 978-3-941159-39-6
