### ISSUE TITLE
library empty, zotero.sqlite size of 0 kb

### ISSUE THREAD

**Issue by galantra** [Juris-M/zotero#73]
I posted this on https://forums.zotero.org/discussion/comment/347960#Comment_347960 and _adamsmith_ advised me to bring it to your attention.

> I have a problem which is not described in the documentation, I believe.
> 
> I installed and began using Juris-M only a few days ago. I had a custom location for Zotero/Basisverzeichnis and Zotero/Datenverzeichnis on an internal HDD, because I did not want all the PDF copies on my SDD.
> Yesterday, I put my laptop into stand-by, having kept Juris-M open. This morning, I woke Windows 10 up (leaving stand-by) and all of my library was gone. I then closed and re-opened Juris-M a few times.
> After closing it, an error appeared. It was unable to load translators and styles.
> I unchecked automatic syncing and disconnected my Zotero online profile from Juris-M. The online library is still integer, as it was yesterday.
> My zotero.sqlite file has a size of 0 KB. I read that an empty database should be either 1 MB or 5 MB.
> I have no zotero.sqlite.*bak files (I checked with LookDisk).
> I then made a backup by copying the folder called "Zotero".
> I opened Juris-M again and now it is "Installing 212 jurisdictions".
> 
> A solution, I think, would be to sync my online library to the laptop. How can I do this? If I understood the documentation correctly, I can simply reconnect my online profile to Juris-M and it will sync the online content to the laptop.
> 
> […]]
> 
>     moebio
>     6 days ago
>     I could resolve the problem: I logged in and synced. This downloaded the data form the server to my laptop.

**Comment by fbennett** [comment]
@galantra I'm very sorry for taking so long to respond to your post. Do you still need help with this issue?

**Comment by galantra** [comment]
Thanks for reminding me about this. The issue is solved. I did what I devised, and synced the online library to the laptop.
