### ISSUE TITLE
All Notes Display as "[]

### ISSUE THREAD

**Issue by quowarranto** [Juris-M/zotero#74]

**Comment by quowarranto** [comment]
Juris-M 5.0.89m1 was expected to have all (or almost all) untitled items should show a descriptive title in the center pane.

Instead, all notes display "[]" instead of the first line preview.

<img width="556" alt="Screen Shot 2020-07-03 at 4 20 42 PM" src="https://user-images.githubusercontent.com/62404861/86495992-6308ba00-bd49-11ea-8144-c12c23ddea28.png">

**Comment by fbennett** [comment]
Thanks for the report. I'll work on this today.

**Comment by fbennett** [comment]
I've tracked down the bug, and have a fix for it in the queue. A release with the fix will be available in a few hours.
