### ISSUE TITLE
no-repeat implementation

### ISSUE THREAD

**Issue by fbennett** [Juris-M/zotero#79]
As I understand requirements: A no-repeat attribute on `cs:group` taking a list of variable names as argument should suppress the group when all of the values of the listed variables match those of the immediately preceding item in the same citation, if the items are not linked with a relation.

To confirm, when no-repeat is implemented, will it be correct to treat the items as separate entries in the bibliography?
@georgd

**Comment by georgd** [comment]
@fbennett yes, both Statements are correct.

**Comment by georgd** [comment]
IIRC, your implementation from last year did it right :)

**Comment by fbennett** [comment]
The code was overwritten when the parallel-cite functions as a whole were rewritten. Working on it.

**Comment by georgd** [comment]
Thanks! I’m sorry if it looked like I meant to hurry you. I just thought you might be able to reuse (parts of) that code.

**Comment by fbennett** [comment]
This should be working now. https://github.com/Juris-M/citeproc-js/commit/2c1f2eb2c6f0dfeb7cf5e62da814c2a0cae5800b
