### ISSUE TITLE
Feature Request: Remember columns and sorting per subcollection, saved column and sorting settings

### ISSUE THREAD

**Issue by KarlHegbloom** [Juris-M/zotero#8]
I have a subcollection for books and law journal articles. For that, I want one column and sorting setting. I have another subcollection for caselaw. For that, I want a different column and sorting setting. I'd like it to remember those when I click back and forth from one to the other.

I'd also like to be able to save and recall column and sorting settings, to easily switch between views.

I'd like to be able to customize the columns the way that Zotfile lets me customize the file renaming. Perhaps then I'd not need separate settings between a subcollection of law journal articles and caselaw, and I could mix them in one view or subcollection. For example, I'd like a column that is Reporter when it's a case, and Journal when it's a journal article. Then Volume Reporter|Journal Pages would make a good triplet for columns.

As it stands, in order to add custom fields to Zotfile's file renaming feature, you have to hand-edit json. A general purpose interface for that would be nice to have. Perhaps the same interface would work for both the file renaming and the column settings then? I don't know if it's related to CSL but I bet it is.

It would also be useful to have similar settings wrt columns and sorting for the dialog for selecting related items. In there, perhaps a search based narrowing would be good as well... though then I can just click on a saved search right?

**Comment by fbennett** [comment]
Sorry for the _very_ long delay in responding. This would add quite a bit of complexity to the code behind the UI. I'm trying to avoid playing too many (more) tricks in Juris-M, especially in the UI, to keep the maintenance burden under control. Would be better to lobby Zotero on this. If they introduce more flexible handling of sort columns, it would feed through into Juris-M as a routine code update from upstream.
