### ISSUE TITLE
Add `division` to the Jurism UI

### ISSUE THREAD

**Issue by georgd** [Juris-M/zotero#80]
Austrian styles will rely on the `division` variable for court sub-divisions, even if the divisions are available in the abbreviation files. Showing this field in the UI would simplify things.

Reason: within a string of citations, immediately subsequent references to different cases from the same court don’t repeat the court name. However, relevant* subdivision information is stated with each single reference. The current structure of the abbreviation mechanism doesn’t allow this so resorting to `division` seems the next best choice.

Ex: two citations in a string relating to different cases of decided by the court "OGH". The first by a ordinary court composition, the second by a reinforced senate of judges ("verst Senat"):

`OGH 2 Ob 328/97t; (verst Senat) 6 Ob 24/11i.`

(* 1st Chamber, 2nd Chamber... don’t seem relevant contrary to Great Chamber and similar)

**Comment by fbennett** [comment]
Understood. I hadn't thought of it from that angle, but that makes a lot of sense.

**Comment by fbennett** [comment]
This has been added to the client, and will appear in the next release, immediately below the Court field.
