### ISSUE TITLE
Add locator `margin-number`

### ISSUE THREAD

**Issue by georgd** [Juris-M/zotero#82]
In German language legal literature, paragraphs or groups of paragraphs are usually consecutively numbered in the page margin. If present, these margin-numbers are preferred to any other pinpoint. Currently, legal styles misuse one of the lesser used locators. It’s definitely not viable to use `paragraph` instead, as this locator is used in legal texts on its own right.

As this is a central feature of German legal citation, a new locator `margin-number` should be added.

**Comment by fbennett** [comment]
Our extended locators each have a short-code (para. for paragraph, sec. for section etc.). Each is a single string of lowercase roman characters. What would be a suitable short-code for margin-number?

**Comment by georgd** [comment]
That’s not a code but a string for display, isn’t it? TBH, I don’t know what the correct short form in English would be. I even had problems to find an English translation for the German ‘Randnummer’ or ‘Randziffer’. Perhaps `m-n.`?

The German names are `Randnummer` and short: `Rn`.

**Comment by fbennett** [comment]
The short-codes are used to set a localizable term directly in the field.
That gives us a much larger set of labels than those supplied by the UI.
"rn." seems a good candidate for this one: when the term is undefined, it
reverts to the literal short-code (without localization or pluralization).
That reminds me to ask: is there a pural form of Rn.?

**Comment by georgd** [comment]
Thanks for the explanation. There's no specific plural form of the short
form. The full form's plural is `Randnummern`.

Frank Bennett <notifications@github.com> schrieb am Mo., 28. Sep. 2020,
08:19:

**Comment by denismaier** [comment]
That would be a good addition, yes. Perhaps we should consider this for csl 1.1. @bwiernik wdyt?

**Comment by fbennett** [comment]
This should now to working in ``citeproc-js`` 1.4.26 (commit at https://github.com/Juris-M/citeproc-js/commit/58adb58e578676f8cde1f3f336341f61acc4948e#diff-749fde5b44f91ad90a2478a03e8e8bd6L81). ``citeproc-test-runner`` and the Jurism beta have been updated to the new processor. Documentation [here](https://citeproc-js.readthedocs.io/en/latest/csl-m/index.html#locator-terms).

**Comment by bwiernik** [comment]
@denismaier @georgd  don't see any issue with more locators--that's just a simple lookup table. Can you consolidate locator suggestions into the issue you opened on the CSL schema repo for it?
