### ISSUE TITLE
Inheritable name options not working reliably

### ISSUE THREAD

**Issue by georgd** [Juris-M/zotero#83]
While testing all the great new features with Jurism, I stumbled over this:

Both jm-legcit styles declare `name-delimiter="/"` but this is not applied in citations and bibliography when using Jurism. The macros look like this:

```
  <macro name="editor-short">
    <names variable="editor">
      <substitute>
        <names variable="collection-editor"/>
        <names variable="container-author"/>
      </substitute>
    </names>
  </macro>
```

 I have to explicitly add `<name delimiter="/"/>`. 

I now remember having seen this before with citeproc-test-runner as well, but only on the `author` name. That’s why the author macro was changed accordingly a while ago to work around this.

Is that desired behaviour in CSLm?

**Comment by denismaier** [comment]
Sidenote: I don't know if this particular case is desired in CSLm, but I've also had the impression before that inheritable attributes don't work reliably.

**Comment by fbennett** [comment]
It may take some time for me to get to this, unfortunately. Meanwhile, if
you come up with a specific test that illustrates the failure, a pull
request against the citeproc-js fixtures/local repo would be welcome.

**Comment by georgd** [comment]
> It may take some time for me to get to this, unfortunately.

It’s not a show-stopper as it’s quite simple to work around it.

> Meanwhile, if you come up with a specific test that illustrates the failure, a pull request against the citeproc-js fixtures/local repo would be welcome.

I’ll do (tomorrow).

**Comment by fbennett** [comment]
The issue with ``name-delimiter`` has been fixed.
