### ISSUE TITLE
Documents break when adding `legal_commentary` and `legal_case` in the same document

### ISSUE THREAD

**Issue by georgd** [Juris-M/zotero#84]
Testing both `jm-legcit` styles with Jurism and Word, I get this:

![image](https://user-images.githubusercontent.com/214002/94486071-2bda6580-01df-11eb-8b6f-7cf5c77b8ad0.png)

This happens, when I cite `legal_case`s  and `legal_commentary`s in the same document.

How can I help with debugging this?

Edit: this happens with both styles at the moment when I add the second of the two types:

1. cite a `legal_commentary`
2. cite a `legal_case`

or

1. cite a `legal_case`
2. cite a `legal_commentary`

**Comment by fbennett** [comment]
Found the bug. Will rebuild shortly, after resolving the comma-safe issue.

**Comment by fbennett** [comment]
The bugfix is included in the latest Jurism beta.

**Comment by georgd** [comment]
Working great now! Thanks!
