### ISSUE TITLE
Add Juris-M locators to dropdown in citation dialogue

### ISSUE THREAD

**Issue by georgd** [Juris-M/zotero#85]
Wondering how the extended CSLm locators are to be used, I propose adding them to the citation dialogue. It seems to me that it’s as simple as adding them to https://github.com/Juris-M/zotero/blob/db629fa16f648c06ff939ab3cf7ddbabce9c31af/chrome/content/zotero/xpcom/cite.js#L11-L13

Does anything speak against this?

**Comment by fbennett** [comment]
It's a huge list.

**Comment by georgd** [comment]
I know. But how do you apply a locator from the extension? At least `randnummer` and `article` are crucial for us. Most of the others are subordinate and won’t usually be entered on their own (at least until CSL 1.1 will be introduced).

**Comment by fbennett** [comment]
Ah - that needs documenting. If you leave the dropdown as "page" and just start the locator field with "rn.", "art.", "sec." etc. it will render the localized term. (And at least for me, I find that more convenient when I'm writing than reaching for the dropdown.)

**Comment by georgd** [comment]
:D I thought already that you implemented something like that and I even guessed in the right direction. But I tried without the trailing `.`.

Edit: just tried it — works perfectly. I hope, the users will like it as I do :)
