### ISSUE TITLE
Synchronisation error "Invalid property 'division'"

### ISSUE THREAD

**Issue by georgd** [Juris-M/zotero#87]
Each time, Juris-M synchronises the db, a red exclamation mark appears, complaining `Invalid property 'division'`. Is perhaps the mechanism missing that puts the `division` in the `extra` field for synchronisation with the Zotero servers?

**Comment by fbennett** [comment]
Thanks for the report. I'll test locally and get a fix in place.

**Comment by fbennett** [comment]
Found the bug, will be fixed in the next beta release.

**Comment by fbennett** [comment]
Beta with the fix is available now.

**Comment by fbennett** [comment]
When the style is ready, let me know and we'll merge your styles and modules into the respective masters for inclusion in a full client release.

**Comment by georgd** [comment]
Great, thanks!

These are my plans:
- During the next week finish the three legcit styles and the IBFD style and create the corresponding PRs against the Juris-M repos.
- In the weeks after that get the second Austrian style on the road and try consolidation of `juris-at.csl`.
- Try improving other jurisdiction style-modules where possible for me.

**Comment by fbennett** [comment]
What would be suitable timing for the first Jurism client release with all of our changes? It can be followed by others as further pieces fall into place, but there are a bunch of general bug-fixes in the work, and it will be good to release it when you feel the features you need have stabilized.

**Comment by georgd** [comment]
If I don't hit any bug by accident, I think the features are complete
(except for the punctuation consolidation) and once I have finished the
styles, it can happen. End of next week seems doable to me.

Frank Bennett <notifications@github.com> schrieb am Sa., 3. Okt. 2020,
13:01:
