### ISSUE TITLE
`eu.int:cjeu` doesn’t trigger using style-module `eu.int`

### ISSUE THREAD

**Issue by georgd** [Juris-M/zotero#89]
I discovered that when citing a case in Word with `jurisdiction: eu.int:cjeu`, the `eu.int` style-module isn’t called. However, when I change the jurisdiction in Juris-M to `eu.int`, the styles work as desired. The citeproc-test-runner works correctly there.

This might be the same as reported here in August: https://forums.zotero.org/discussion/84523/juris-m-use-of-para-instead-of-brackets-for-cjeu-cases-in-oscola/p1

**Comment by fbennett** [comment]
Bug found and fixed. It was blindly collapsing jurisdiction data to a single arbitrary language when several were available, which masked the default, resulting in to cached data unless the client was configured to use the default. Thanks for pressing on this. https://github.com/Juris-M/zotero/commit/55b35799f411dc1cd7d352523a62923b874750f0
