### ISSUE TITLE
dateparser: loading turkish months makes september the 7th month

### ISSUE THREAD

**Issue by retorquere** [Juris-M/zotero#9]
```
Zotero.DateParser.addDateParserMonths(["ocak", "Şubat", "mart", "nisan", "mayıs", "haziran", "temmuz", "ağustos", "eylül", "ekim", "kasım", "aralık", "bahar", "yaz", "sonbahar", "kış"]);

console.log(Zotero.DateParser.parseDateToObject("September 20, 2006"));
```

yields

```
{ month: '7', year: '2006', day: 20 }
```

**Comment by fbennett** [comment]
This is now fixed. I hadn't anchored the regexp to the start of the target string, and it was matching September on "tem".

Note that Juris-M now uses the [citeproc-js date parsing module](https://bitbucket.org/fbennett/citeproc-js/src/tip/src/util_dateparser.js?at=default&fileviewer=file-view-default) directly.

**Comment by retorquere** [comment]
What do you mean with "directly"?

**Comment by fbennett** [comment]
Juris-M reuses the code of the `citeproc-js` module, rather than copying it:

https://github.com/Juris-M/zotero/blob/jurism/chrome/content/zotero/xpcom/dateparser.js

(I hadn't pushed the change yet, sorry of that was a source of confusion.)

**Comment by retorquere** [comment]
Ah, now it makes sense :+1:
