### ISSUE TITLE
Citing legal documents in Word and LibreOffice produces an error

### ISSUE THREAD

**Issue by georgd** [Juris-M/zotero#90]
> Zotero integration error: Zotero experienced an error updating your document. Would you like to view troubleshooting instructions?

This happens when citing a document of type `regulation`, `bill`, `statute` or `treaty` with the three jm-leg-cit styles, with the jm-indigobook-law-review, and the jm-indigobook-law-review-2 styles. It doesn’t happen with jm-indigobook, v-en-a or jm-ibfd. The items, I tested with, are from the "Jurism Test Style Items" group.

During the last 24 hours I have tried to chase down the bug but without success. I even replaced the entire `jurism` macro in the jm-leg-cit styles with the macro from jm-indigobook and removed the `jurisdiction-preference` but that didn’t help either. The styles work well with citeproc-test-runner.

Finally, I diffed jm-indigobook and jm-indigobook-law-review and the only relevant difference seemed to be the `class="in-text"`. Changing the class to `in-text` in the jm-leg-cit styles, makes them work again. 

So, the bug seems to appear in note-styles that use style-modules (v-en-a and jm-ibfd don’t).

@fbennett, could you please have a look, what’s happening there?

**Comment by fbennett** [comment]
Just came off teaching for the week, I'll have a look! Remember you can always submit a bug report via Help -> Debug Output Logging, as in Zotero. (The Jurism reports are sent to a Jurism server to which I have access.)

**Comment by fbennett** [comment]
Bug found and fixed. https://github.com/Juris-M/citeproc-js/commit/b06fbc44eea62c4f685f392194f6c1537c98ff88
