### ISSUE TITLE
Jurisdiction can’t be deleted

### ISSUE THREAD

**Issue by georgd** [Juris-M/zotero#91]
Once a jurisdiction is entered in an item, that field can’t be cleared any more. That might be good with `legal_case`, `legislation` and so on but not with `report` which is mostly not tied to a jurisdiction. It should be possible to clear erroneous entries in that field.

(A possible workaround currently is to delete the field in the synced online library.)

**Comment by fbennett** [comment]
This is fixed in code, and the fix will appear in the next release. There was code in there to enable deletion, but it wasn't working for reasons lost in the mists of time. https://github.com/Juris-M/zotero/commit/c1e771153b7e707e1f86fce3fd65abbdafe7b08b
