### ISSUE TITLE
leg-cit style modules not included in release

### ISSUE THREAD

**Issue by georgd** [Juris-M/zotero#92]
This time, I wiped all jm-*, and juris* files and folders and the style-modules folder in order to simulate a mostly clean install before installing the new release. As citing a legal case gives me a no-printed-form error, I found out that the leg-cit style modules weren’t installed.

**Comment by fbennett** [comment]
Thanks for testing! Just checked, and I had pulled the modules into the ``citeproc-js`` project, but didn't pull them separately into ``jurism`` before the build. Some of the other things have been fixed, and I've made some backward-compatible progress on the abbrevs localization issue. When I reach a good stopping point this evening I'll tie off and make another set of releases.

**Comment by fbennett** [comment]
The 5.0.90m6 release update is now available, for all three platforms. It includes fixes for a few papercuts:
- The Jurisdiction value can be reset to empty in the Report, Journal Article, Newspaper Article, and Standard types.
- A compiler bug affecting inheritance of values for the human-readable short-form of the Jurisdiction code has been fixed, with updates to the ca and eu.int jurisdictions.
- Jurisdiction names now localize properly in the UI.
- The LegCit style modules are now included (ouch).

https://juris-m.github.io/release/
